### ISSUE TITLE
srfi-88/89 support, keyword arguments

### ISSUE THREAD

**Issue by jhidding** [cisco/ChezScheme#108]
Are there plans to support srfi-88 and 89 (self-evaluating keywords and keyword arguments) in the future? What would be needed?

**Comment by Saigut** [comment]
Since srfi is like a library, maybe you can use srfi-88/89 by yourself. If you want srfi-88/89 to become the scheme standard, maybe you should request to Scheme Reports Process.

**Comment by jhidding** [comment]
Not for this SRFI; it's really a 'request for implementation'. Srfi-88 proposes a syntax where symbols ending with ':' are self-evaluating to objects of a new type `keyword'. Many implementations already support this in some form not necessarily compatible with each other. Keyword arguments are an important tool for not needing to remember the order of long lists of arguments, and support a literate style of programming. However, they are impossible to implement on a scheme that doesn't already support self-evaluating keywords, other than writing another scheme on top. I'm not sure why they haven't entered into R6RS or even R7RS-small.

**Comment by Saigut** [comment]
Sorry, I did't check the details about those two srfi.

**Comment by ovenpasta** [comment]
Hi, I think a starting point could be to quote the symbols ending with :
I think that could be done from s/read.ss but I couldn't figure out how.
Isn't there a possibility in chez scheme to customize the reader (I mean
without modifying the chez scheme source code)

**Comment by NalaGinrut** [comment]
hi folks!
I really care about this feature, any progress?

**Comment by dybvig** [comment]
I've never encountered a use for keyword arguments that wasn't better handled by records or macros (both of which effectively push correctness checking and overhead from run time to compile time).  Furthermore, implementing SRFI 89 with the best possible efficiency would be quite a bit of work and add complexity to various parts of the compiler and run-time system.  The SRFI 88 change to treat certain identifiers as self-evaluating is both unnecessary (see below) and not backward compatible.  So I don't foresee adding support for either SRFI.

SFRI 89 can be implemented at the source level along the lines of the code given in the SRFI description (although I would use `symbol-hash` to speed up the hashing process), and a suitable replacement for SRFI 88 in almost all cases would be to define keywords as identifier macros, e.g.:
```
(define-syntax color: (identifier-syntax 'color:))
```
so that the identifier `color:` becomes, in effect, self-evaluating.  This is actually better than having all symbols ending in colons be self-evaluating, because a misspelling is potentially caught at compile time.

**Comment by dybvig** [comment]
Have you tried defining keyword markers as identifier macros as I suggested?  If so, in what way does not suffice?

**Comment by NalaGinrut** [comment]
Yes, I can use your trick with case-lambda to bind similar things, but it means we have to spend lot of time to write such wrapper. And for each different keywords in existing code, we have to define syntax for the keyword.

Your proposal is good for education purpose, but not for real product development.

**Comment by laqrix** [comment]
Maybe checkout something like this: https://github.com/laqrix/raytracer/blob/master/defaults.ss

I use it to make an XML-like language for raytracing, but its core, it's about named parameters without any runtime cost.

**Comment by jessymilare** [comment]
With this discussion, it seems many people here don't know the meaning and
the importance of standardization, portability of code, specifications,
etc. As if it didn't matter that there is an accepted specification of
keywords, everyone should make a hack to create keywords or something
similar.

Em qui, 3 de mai de 2018 19:01, laqrix <notifications@github.com> escreveu:

**Comment by jhidding** [comment]
@jessymilare I agree wholeheartedly!

I think the link @laqrix sent is an excellent example of why syntax-case macros are not the best way to solve this issue. The code looks unreadable to me, and I think it is very hard to debug. Also I find the entire idea of creating an identifier-syntax for every keyword argument not very attractive. I guess the Racket method of writing a stack of language readers is the preferred option here, and also in the other issue on R7RS (issue #279).

I could think of one way to go about it: write a reader that translates to R6RS code and subsequently compiles and runs that code. In the case of adding keyword arguments this could be a relatively tight setup. The next question is: Is this the recommended way to build another scheme on top of chez?

**Comment by NalaGinrut** [comment]
The standardization is helping Scheme to get rid of Lisp curse, which means people always reinvent wheels since it's too powerful to make it when you master this language.

But no, it's curse, not any gospel. The power of Scheme is not encouraging us to write more unecessary wheels, but a warning to make us hold the horses.

I'm not asking for a method to support optional arguments, neither a method to mimic keywords. I'm asking for an abidience for the standardization. SRFI is the defacto standard of Scheme library, any Scheme should try to be compatible with it.

I respect @dybvig and his work, and it's a reasonable request to beg for the reconsideration. I think ChezScheme shouldn't care too much about the performance, the more reasonable way is to provide mechanism, and if users don't worry about the performance too much, they could use it, but if they do, they can find other way. Let the users choose the policy, please!

**Comment by jltaylor-us** [comment]
Have any of you attempted to write the `define-syntax` for SRFI 89 `define*` and `lambda*` using the currently available Chez Scheme language, as Dybvig suggested?  Looks to me like it's possible with zero changes to Chez Scheme.

As an aside, SRFIs are not part of The Scheme Programming Language.  If you want to write portable, r6rs-compliant code then you can't rely on any of them being available.  If you want a language that throws in whatever features some group of users decided they wanted without regard to backwards compatibility or consistency with the rest of the language then perhaps you would be more comfortable writing in, say, Ruby or Python instead.

**Comment by NalaGinrut** [comment]
Boost was not part of C++ , but it's been popular for decades, and its many features are adopted to C++14 now. It's great progress for C++ to admit the value of boost and positive cooperate with boost community. It's double win.  So what is the similar situation between SRFI and Scheme? Positive cooperate, or ignored it's value?

To my understand, what @dybvig suggested could implement define* and an alternative keywords with symbols. But it means people have to write macros to define the necessary keywords in advanced, no?

If yes, then it's what I said, good for educational purpose, but not for real product, the latter always have large code base, this become unmaintainable.

If no, then could you write me a prototype without predefined keywords, or auto generate the keywords?

**Comment by dybvig** [comment]
I appreciate all of the input on this thread.  A couple of clarifications are in order.  First, SRFIs are not standards and are vetted, for the most part, only by people who are interested in the mechanism.   As a result, the mechanisms they describe do not necessarily make sense for every implementation.  Some might eventually be standardized, but no one should feel obligated to support one just because it has been put out there.  Of course, some don't require special support from the implementation, and it's unfortunate that SRFI-88/89 do.  Second, Chez Scheme's main design principles are efficiency and reliability.  This includes supporting efficient and reliable mechanisms, and a keyword-argument mechanism that requires run-time lookups is neither.

I would consider adding support for something like SRFI-88 keywords in order to facilitate user definitions of SRFI-89 if doing so didn't require an incompatible change to the lexical syntax and didn't complicate the language and implementation with an otherwise unnecessary new datatype.   Again, it's unfortunate that SRFI-88/89 were designed to require it.

Incidentally, I am not sympathetic with the notion that it's difficult or unmaintainable to declare keyword-argument names.  In the major software systems I've been involved with, declarations similar to this are used to improve reliability and documentation.  In this case, declaring the valid keyword-argument names might save one from shipping a piece of software with a misspelled keyword-argument name that causes a failure in a critical customer installation.  To lessen the burden, it would be straightforward to implement a variant of `define*` that defines the keywords along with the procedure name.

**Comment by jhidding** [comment]
@dybvig thank you for the discussion, I consider the matter closed.

**Comment by johnwcowan** [comment]
Not reopening this issue for Chez, but just in general:

dybvig writes:

> I've never encountered a use for keyword arguments that wasn't better handled by records or macros (both of which effectively push correctness checking and overhead from run time to compile time). 

I agree that having a macro facade over an ordinary procedure is a Good Thing.  The trouble is that you have to decide in advance whether you are going to have keywords in future, because a macro is not a drop-in replacement for a procedure.  Indeed, `apply` is always the Achilles heel of all non-CL-style keyword systems: you end up needing a completely separate funcall or apply procedure, as Racket has done and SRFI 177 (in progress) proposes.  At best, using regular apply is equivalent to specifying no keywordses at allses.

As for records, without a keyword-ish kind of record constructor it is a great pain to use regular BOA constructors to pass a record full of dozens of keyword values only a few of which are being set.  It's equivalent to using a *whole lot* of ordinary arguments and hoping you don't screw up where the various `#f` arguments (or whatever) go.  So they just push off the keyword problem to a lower level.
