### ISSUE TITLE
format produces and error

### ISSUE THREAD

**Issue by brorbw** [cisco/ChezScheme#111]
So during a course on functional programming I had to implement a "mini-format" procedure that produced somewhat the same output as the built-in "format" procedure from Scheme, and then i noticed some weird behavior from "format".

> (format "\\~")

The interpreter crashes and yield that there are unbalanced parentheses

**Comment by jltaylor-us** [comment]
It's pretty unlikely that either `format` or the interpreter or the REPL is crashing.
It doesn't render this way on the github website, but the email version said you are trying to do `(format "\~")`.  The character sequence `"\~"` is not a valid string in r6rs, because `\~` is not a valid backslash escape.  The REPL probably should do something more useful than open a string that it will never close (although you can reset it back to the prompt with `^C`).

Incidentally, I'm guessing maybe you were really trying to say `(format "~~")`?

**Comment by brorbw** [comment]
I am aware that it is not at valid input.
But the REPL should do something more useful. However i have tried "\~"" as well and it produces the same behavior. Im also aware that you can reset it with ^C

**Comment by dybvig** [comment]
The REPL refuses to accept invalid input when you hit enter so you can edit partial and mal-formed intermediate forms of the input.  You can force an attempt to accept the input with `^J` to see why it's not accepting the input.  In this case, you'd get a message identifying backslash-tilde as an invalid string character.

**Comment by brorbw** [comment]
I see. The problem is actually the string itself.
