### ISSUE TITLE
Could this be a bug in Chez Scheme? Variables magically changing value

### ISSUE THREAD

**Issue by rain-1** [cisco/ChezScheme#116]
Hello!

I found something strange when working on an extensible pattern matcher in Chez. Here's a minimal test case:

```
> (library (a)
    (export a)
    (import (scheme))

    (define a (box #f)))
(library (b)
    (export foo a)
    (import (scheme) (a))

    (define (foo) (display 'hello-world))

    (set-box! a #t))
```

```
> (import (b))
> a
#&#f
> (foo)
hello-world
> a
#&#t
```

Is this the correct behavior?

**Comment by akeep** [comment]
No, this is expected behavior.  (import (b)) makes the exports from library
(b) available, but it does not cause any code to run.  The library
initialization code, in this case, setting the definition of foo and
resetting the value of box a, are not done until the one of the
non-syntactic exports is actually accessed.

In R6RS Scheme, there is no guarantee of when or how many times
initialization code will be run.  In Chez, we endeavor to run it only once,
the first time an export of the library is referenced in a given Scheme
session, other implementations, like Racket's R6RS implementation for
instance, runs the initialization code for each phase the library is
referenced in, effectively this could cause a to be set and reset over the
course of the library load.

In Chez, there are three phases for an library: import, visit, and invoke
(also known as revisit).  Import, which happens when the library is
imported, (import (b)), only sets up the bindings in Chez's syntactic
environment, visit, which happens the first time an exported macro is
referenced, sets up the syntactic transformers and the compile-time
environment, and invoke, which happens the first time a non-macro export is
referenced, sets up the values of the definitions and runs initialization
code.

In general, if you have initialization code you'd like to run at a
particular point, it is best to simply wrap that initialization code in a
function and call it explicitly.

(library (b)
  (export foo a)
  (import (scheme) (a))

  (define (foo) (display 'hello-world))

  (define (initialize-b) (set-box! a #t)))

-andy:)

On November 13, 2016 at 4:37:26 PM, rain-1 (notifications@github.com) wrote:

Hello!

I found something strange when working on an extensible pattern matcher in
Chez. Here's a minimal test case:

> (library (a)
    (export a)
    (import (scheme))

    (define a (box #f)))
(library (b)
    (export foo a)
    (import (scheme) (a))

    (define (foo) (display 'hello-world))

    (set-box! a #t))

> (import (b))
> a
#&#f
> (foo)
hello-world
> a
#&#t

Is this the correct behavior?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cisco/ChezScheme/issues/116>, or mute the thread
