### ISSUE TITLE
Foreign Interface function strcpy don't work

### ISSUE THREAD

**Issue by netmany** [cisco/ChezScheme#119]
in the standard libc function strcpy, we can't get destination from source;
char * strcpy ( char * destination, const char * source );
and doing some test shows failing to transfer value out through function param in Foreign Interface
(foreign-procedure entry-exp (param-type ...) res-type)

the following is the execution commands:
```scheme
 (load-shared-object "libc.so.6")
 (define strcpy (foreign-procedure "strcpy" (string string) string))
 (define from "some random texts")
 (define to (make-string 1024))
 (strcpy to from)
"some random texts"
 to
"\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;
```

**Comment by jltaylor-us** [comment]
From http://cisco.github.io/ChezScheme/csug9.4/foreign.html#./foreign:h2 documentation on conversion of parameters done by the function returned by `foreign-procedure`:
> `string`: This type is an alias for `utf-8`.
> `utf-8`: The argument must be a Scheme string or `#f`. For `#f`, the null pointer (0) is passed to the foreign procedure. A string is converted into a bytevector, as if via `string->utf8`, with an added null byte, and the address of the first byte of the bytevector is passed to C.

So the pointer passed to the first argument of the C strcpy function is not the same as the pointer to the scheme string `to`... which is good, because scheme strings and C strings are not the same thing, and things would go horribly awry if C wrote all over the memory that was supposed to be a scheme string.

**Comment by netmany** [comment]
Then, how to define strcpy in scheme foreign interface to make it work?

**Comment by netmany** [comment]
In the example code of foreign interface: https://cisco.github.io/ChezScheme/csug9.4/foreign.html#./foreign:h9
The c_read also don't work as expected;
int c_read(int fd, char *buf, unsigned n);

(define c-read
  (foreign-procedure "c_read" (integer-32 string integer-32)
    integer-32))

 (define get ; procedure to read data from client
    (let ([buff (make-string 1024)])
      (lambda ()
        (let ([n (c-read client-socket buff (string-length buff))])
          (printf "client:~%~a~%server:~%" (substring buff 0 n))))))

The param value of buf can't pass out!

**Comment by jltaylor-us** [comment]
The examples in the documentation are out of date, but the two files referenced (`examples/csocket.c` and `examples/socket.ss`) are up to date in the repository.

**Comment by akeep** [comment]
@jltaylor-us is correct as to why this doesn't work.  The ``string`` foreign type is really just a convenience for converting from a Scheme string into a C string (which is allocated in at a different memory location from the string).

In general when you have a pointer type that you want to get back, you have to pass in a pointer to some allocated space.  For instance, you can use ``foreign-alloc`` to allocate space outside of the Scheme heap to pass to the C procedure to use for its return.  You could handle all the marshaling yourself (as I have in this code example) or use a mix of ``string`` for arguments that are _input_ arguments and foreign allocated space for things that are _output_ arguments.  Remember, when you use ``foreign-alloc`` you also need to use ``foreign-free`` to free it, similar to C's malloc.

```racket
(define strcpy
  ;; define foreign procedure
  (let ([$strcpy (foreign-procedure "strcpy" (void* void*) void*)])
    (lambda (str)
      (let ([fsize (fx* (ftype-sizeof char) (fx+ (string-length str) 1))])
        ;; allocate foreign space for source and destination
        (let ([src (foreign-alloc fsize)]
              [dst (foreign-alloc fsize)])
          ;; marshall Scheme string into C string
          (do ([i 0 (fx+ i 1)])
            ((fx= i (string-length str)))
            (foreign-set! 'char src i (string-ref str i)))
          ;; call strcpy
          (let ([dst-also ($strcpy dst src)])
            ;; check that our result was what we expected
            (unless (= dst-also dst) (errorf 'strcpy "returned unexpected destination pointer"))
            ;; marshall C string into Scheme string
            (let ([dst-str (let f ([i 0])
                             (let ([c (foreign-ref 'char dst i)])
                               (if (char=? c #\nul)
                                   (make-string i)
                                   (let ([dst-str (f (fx+ i 1))])
                                     (string-set! dst-str i c)
                                     dst-str))))])
              ;; free our foreign allocated memory
              (foreign-free src)
              (foreign-free dst)
              ;; return the string
              dst-str)))))))
```

This works as you might expect:

```racket
> (strcpy "foo") ;=> "foo"
```

However, it is a bit verbose.  Following from the corrected version of the example, which @jltaylor-us pointed out is checked into the examples repository, you can use the ``u8*`` type to pass a Scheme allocated byte vector that C can write into.  You could re-implement the solution above, as follows:

```racket
(define strcpy2
  (let ([$strcpy (foreign-procedure "strcpy" (u8* u8*) void*)])
    (lambda (str)
      (let ([dst (make-bytevector (string-length str))])
        ($strcpy dst (string->utf8 str))
        (bytevector->string dst (native-transcoder))))))
```

This is quite a bit simpler, but is a bit of a cheat, since technically we should be ensuring our byte vector is null terminated before we pass it in, and we should be providing a byte vector with space for the null terminator, but if we do that we also will need to trim off the final null character of the string.  The ``u8*`` is something that can be used in general to provide Scheme allocated space to C, but should be used with a bit of caution, since a misbehaved C function could write all over the Scheme heap starting from that pointer if you are not careful.

As far as the documentation, we should clean that up by making use of the example code from the repository.

**Comment by netmany** [comment]
after modify strcpy declaration as following, it works.
(define strcpy (foreign-procedure "strcpy" (u8* string) string))
(define from "some random texts")
(define to (make-bytevector (bytevector-length from)))
(strcpy to from)
(utf8->string to)

but it still don't work in reading out from file through the foreign interface u8*:
======================================
// native.c

#include <fcntl.h>

int myRead(char* filename, char* buf, int len) {
        int fd = open(filename, O_RDONLY);
        if(fd > 0) {
                return read(fd, buf, len);
        }
        close(fd);
        return -1; 
}
========================================
; native.ss

(load-shared-object "./libnative.so")
(define myRead (foreign-procedure "myRead" (string u8* int) int))

(define buf (make-bytevector 1024))
(define len (myRead "./some-log" buf (bytevector-length buf)))
(printf "len=~a\n" len)

(define outBuf (make-bytevector len))
(bytevector-copy! outBuf 0 buf 0 len)
(printf "the res is :~a\n" (utf8->string outBuf))
==================================================
scheme --script native.ss
len=23
the res is :

**Comment by akeep** [comment]
The problem here is not the foreign function interface, you are calling ``bytevector-copy!`` with the arguments in the wrong order.  From http://scheme.com/tspl4/objects.html#./objects:s247:

```scheme
(bytevector-copy! src src-start dst dst-start n) 
```

You have your source and destination reversed.

**Comment by netmany** [comment]
@akeep you're right, the problem has been fixed!
thanks!
