### ISSUE TITLE
Can't build csug

### ISSUE THREAD

**Issue by NalaGinrut** [cisco/ChezScheme#12]
It seems that Makefile of csug uses an author specified path ~/stex/Mf-stex, which is improper for some users. I always put source code to ~/Project. Couldn't stex be a submodule in the Chez repo?

**Comment by rain-1** [comment]
I guess you mean this path:

`./csug/Makefile:installdir=/u/dyb/crs/www/csug9`

**Comment by NalaGinrut** [comment]
That's one of the issues, and there's this:
```
include ~/stex/Mf-stex
```
in Makefile

**Comment by gwatt** [comment]
1. clone github.com/dybvig/stex to your home directory
2. install everything you can possibly find related to tex
3. install netpbm as well
4. find more tex packages to install
5. replace the `installsh` commands in the Makefile to just `install`

**Comment by NalaGinrut** [comment]
@gwatt
First, thank you for reply! And yes, I may compile it with the steps. But what I want to say is that Chez should not assume users use the same specific path, say, ~/stex. This should be fixed for more general case.

**Comment by vmanis** [comment]
I too managed to hack things to generate both csug.pdf and release-notes.pdf. Rather than post diffs or a pull request, I'd like to suggest a few minor adjustments. First, I hope that stex can be distributed with future versions, either as a part of Chez Scheme, or maybe to be installed in a parallel directory, so that all path name references become relative. (This includes references to /usr/bin/scheme; it should just be assumed that the scheme binary is in the path.) Second, I'm not sure whether Transfig is needed; there's a .fig.pdf recipe in csug/Makefile, but there are apparently no fig files. So maybe that can be deleted?

By the way, thanks to everyone involved for making Chez Scheme freely available!

**Comment by dybvig** [comment]
With [this commit to stex](https://github.com/dybvig/stex/commit/3bd2b86cc5ae1797d05fc5cc6f11cc43383f741d) and [this commit to Chez Scheme](https://github.com/cisco/ChezScheme/commit/4bd78a692dd4ca2f88af5d404fd0993a2d141e7b), it should now be more straightforward to build stex and the release notes.  In theory, once you have all of the latex tools in place, you can just run 'configure ; make docs' in chezscheme.

**Comment by vmanis** [comment]
On 2016-05-04 05:47 PM, R. Kent Dybvig wrote:
>
> With this commit to stex 
> <https://github.com/dybvig/stex/commit/3bd2b86cc5ae1797d05fc5cc6f11cc43383f741d> 
> and this commit to Chez Scheme 
> <https://github.com/cisco/ChezScheme/commit/4bd78a692dd4ca2f88af5d404fd0993a2d141e7b>, 
> it should now be more straightforward to build stex and the release 
> notes. In theory, once you have all of the latex tools in place, you 
> can just run 'configure ; make docs' in chezscheme.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cisco/ChezScheme/issues/12#issuecomment-217049039>
>
Perfect! Much appreciated! (And once again, thanks for open-sourcing 
Chez Scheme) -- v

**Comment by NalaGinrut** [comment]
@dybvig Thank you very much!
