### ISSUE TITLE
The code (environment '(rnrs)) becomes slower and slower

### ISSUE THREAD

**Issue by weinholt** [cisco/ChezScheme#122]
Calls to the environment procedure become slower and slower with time. Here's a demo:

```scheme
(define (test)
  (let lp ((i 0)
           (t (current-time)))
    (unless (= i 1000)
      (environment '(rnrs))
      (cond ((zero? (mod i 100))
             (let ((t1 (current-time)))
               (display (time-difference t1 t))
               (newline)
               (lp (+ i 1) t1)))
            (else
             (lp (+ i 1) t))))))

(time (test))
```

The output on my machine:

```
$ scheme --script test-env-perf.ss
#<time-duration 0.000235041>
#<time-duration 0.122254328>
#<time-duration 0.299824438>
#<time-duration 0.639049931>
#<time-duration 0.941928069>
#<time-duration 1.283530203>
#<time-duration 1.690183173>
#<time-duration 2.164652479>
#<time-duration 2.714950215>
#<time-duration 3.125437456>
(time (test))
    9 collections
    16.391116258s elapsed cpu time, including 0.031804202s collecting
    16.401370357s elapsed real time, including 0.031843214s collecting
    81508976 bytes allocated, including 55486320 bytes reclaimed
```

The time durations grow considerably but the expectation is that they should be more or less the same. Other environment procedures do not seem to suffer from the same issue.

Tested with Chez Scheme Version 9.4.1 on Linux amd64.

**Comment by dybvig** [comment]
This is undesirable but expected with the current implementation.  The top-level environment representation employs (system) property lists, with one property per environment for each symbol defined in the environment, and the lookup cost for property lists is linear in the number of properties.  A hashtable per symbol or environment could be used in place of individual system property list entries to reduce the cpu overhead.  It would also be possible to give top-level environments more of a nested structure, like local environments, so they don't always require creation of a new property for each imported identifier.

A compounding issue is that storage space for environments is never reclaimed.  (A comment to this effect appears in the [description of copy-environment](http://cisco.github.io/ChezScheme/csug9.4/system.html#./system:s34).) If it were, the property lists would eventually shrink and the cpu overhead would thereby be limited in examples such as yours.

In general, an environment can't be entirely reclaimed because code compiled against the environment might require some of the bindings, and that code might subsequently be loaded from an object file.  In specific cases, however, environments could be at least partially reclaimed.  Effecting this might be as simple as using weak hashtables for the symbol, environment mappings.  It would also be possible to cache immutable environments created by `environment` and `copy-environment`.

Until someone tackles these issues, applications should arrange to call `environment` only once for each set of arguments when feasible.
