### ISSUE TITLE
compile chez with the CHEZSCHEMELIBDIRS on

### ISSUE THREAD

**Issue by ovenpasta** [cisco/ChezScheme#123]
Hi,
If I compile ChezScheme with CHEZSCHEMELIBDIRS environment variable set, then the compilation fails.
Is this expected? If I unset it then the compilation succeeds.

```
[...]
../bin/ta6le/scheme -q cmacros.so priminfo.so primvars.so env.so setup.so  --script script.all
compiling library.ss with output to library.ta6le
compiling prims.ss with output to prims.ta6le
compiling mathprims.ss with output to mathprims.ta6le
compiling record.ss with output to record.ta6le
compiling 5_1.ss with output to 5_1.ta6le
compiling 5_2.ss with output to 5_2.ta6le
compiling 5_3.ss with output to 5_3.ta6le
compiling strnum.ss with output to strnum.ta6le
compiling bytevector.ss with output to bytevector.ta6le
compiling 5_4.ss with output to 5_4.ta6le
compiling 5_6.ss with output to 5_6.ta6le
compiling 5_7.ss with output to 5_7.ta6le
compiling event.ss with output to event.ta6le
compiling 4.ss with output to 4.ta6le
compiling front.ss with output to front.ta6le
compiling foreign.ss with output to foreign.ta6le
compiling 6.ss with output to 6.ta6le
compiling print.ss with output to print.ta6le
compiling newhash.ss with output to newhash.ta6le
compiling format.ss with output to format.ta6le
compiling date.ss with output to date.ta6le
compiling 7.ss with output to 7.ta6le
Exception: library (nanopass) not found
make[4]: *** [Mf-base:461: bootall] Error 255
make[3]: *** [Mf-base:153: allx] Error 2
make[2]: *** [Mf-base:166: bootstrap] Error 2
make[1]: *** [Makefile:21: build] Error 2
make: *** [Makefile:19: build] Error 2
```

**Comment by akeep** [comment]
You are correct that this is a bug with the build process.

It looks like we are setting the ``library-directories`` explicitly with ``--libdirs`` in part of the build process, but not in all of the places we need to do this.

The problem you are seeing manifest is essentially happening because we are trying to find the [nanopass framework](https://github.com/nanopass/nanopass-framework-scheme) during the compilation process, which we've compiled into the local directory, and if you have ``CHEZSCHEMELIBDIRS`` set to something that does not include the local directory, it cannot find it.

Should be fairly simple to fix once I get a few minutes of spare time.

**Comment by Saigut** [comment]
If you set CHEZSCHEMELIBDIRS to `/xxx/you-lib-path`, Then /xxx/you-lib-path is the only path Chez Scheme to search. But if you plus a colon at the end of that variable, `/xxx/you-lib-path:`, Then `/xxx/you-lib-path` will be added in exist libraries path. Chez Scheme will first search in `/xxx/you-lib-path` and then the paths previously set.

**Comment by rain-1** [comment]
This will also fix https://github.com/cisco/ChezScheme/issues/40

**Comment by dybvig** [comment]
This should be fixed by [this commit](https://github.com/cisco/ChezScheme/commit/1cccd56693911a38ece784da677e35f724950700).
