### ISSUE TITLE
foreign interface: how to pass int* and struct some-type* to C function back and forth?

### ISSUE THREAD

**Issue by netmany** [cisco/ChezScheme#130]
here is my test interface passVal, it doesn't run as expected:
```
$ scheme --script ffi.ss
before passVal/ srcInt=100, dstInt=200, srcStr=some test string, dstStr=
Exception: invalid memory reference.  Some debugging context lost
```

```scheme
; file ffi.ss
(load-shared-object "./libffi.so")

(define passVal (foreign-procedure "passVal" (int iptr string u8* int) int))

(define srcInt 100)
(define dstInt 200)

(define srcStr "some test string")
(define dstStrLen 8)
(define dstStr (make-bytevector (+ 1 dstStrLen) 0)) 

(printf"before passVal/ srcInt=~a, dstInt=~a, srcStr=~a, dstStr=~a\n" 
        srcInt dstInt srcStr (utf8->string dstStr))

(passVal srcInt dstInt srcStr dstStr dstStrLen)

(printf"after passVal/ srcInt=~a, dstInt=~a, srcStr=~a, dstStr=~a\n"                                                                                                                                      
        srcInt dstInt srcStr (utf8->string dstStr))
```

=========================================
```C
// file ffi.c

#include <string.h>                                                                                                                                                                                       

// test ffi arguments passing

#define max(x, y) (((x) > (y)) ? (x) : (y))

int passVal(int srcInt, int* dstInt,
            const char* srcStr, char* dstStr, size_t dstStrLen) {
    *dstInt = srcInt + 1;
    strncpy(dstStr, srcStr, max(dstStrLen, sizeof(srcStr)));
    return 0;
}
```

and what to do with C struct passing?
```C
struct info{
     char* name;
     int age;
}

int getInfo(const char* name, struct info* p){
     // filling some info to p
}
```

```scheme
(define getInfo (foreign-procedure "getInfo" (string stuct-info*) int))
```

**Comment by evilbinary** [comment]
You should read this document  first. https://cisco.github.io/ChezScheme/csug9.4/foreign.html#./foreign:h2

**Comment by netmany** [comment]
@evilbinary plz add some code example to it; the doc need it

**Comment by Saigut** [comment]
```
(passVal srcInt dstInt srcStr dstStr dstStrLen)

*dstInt = srcInt + 1;
```
The dstInt you pass to passVal is exact 200, so *dstInt is looking memory address 200 for an int, and memory address 200 is not a valid memory reference. You'd better not do thing like this before you really understand what you are doing.

**Comment by ChaosEternal** [comment]
think it is better use maillist for such questions.

https://groups.google.com/forum/#!forum/chez-scheme

**Comment by netmany** [comment]
@ChaosEternal the github seems better than google forum for exchanging ideas on scheme outer and inner mechanism discussion;
@ovenpasta the int* can be passed through make-ftype-pointer; but how can a string value in scheme be passed to the (* char) name in a struct info?

```scheme
; file ffi.ss
(load-shared-object "./libffi.so")

(define-ftype PASSVAL_T (function (int (* int) string u8* int) int))

(define passVal (ftype-ref PASSVAL_T () (make-ftype-pointer PASSVAL_T "passVal")))

(define srcInt 100)
(define dstInt (make-ftype-pointer int (foreign-alloc (ftype-sizeof int))))
(ftype-set! int ()  dstInt 200)

(define srcStr "some test string")
(define dstStrLen 8)
(define dstStr (make-bytevector (+ 1 dstStrLen) 0)) 

(printf"before passVal/ srcInt=~a, dstInt=~a, srcStr=~a, dstStr=~a\n" 
        srcInt (ftype-ref int ()  dstInt) srcStr (utf8->string dstStr))

(passVal srcInt dstInt srcStr dstStr dstStrLen)

(printf"after passVal/ srcInt=~a, dstInt=~a, srcStr=~a, dstStr=~a\n"
	srcInt (ftype-ref int () dstInt) srcStr (utf8->string dstStr))

(define-ftype info
     (struct
	 (name (* char))
	 (age int)))

(define getInfo (foreign-procedure "getInfo" (string (* info)) int))

(define ti (make-ftype-pointer info (foreign-alloc (ftype-sizeof info))))

(getInfo "helen" ti)

(printf "info/ age=~d\n"  (ftype-ref info (age) ti))

```
=============================================
```C
// file ffi.c

#include <string.h>

// test ffi arguments passing

#define max(x, y) (((x) > (y)) ? (x) : (y))

int passVal(int srcInt, int* dstInt,
            const char* srcStr, char* dstStr, size_t dstStrLen) {
    *dstInt = srcInt + 1;
    strncpy(dstStr, srcStr, max(dstStrLen, sizeof(srcStr)));
    return 0;
}

struct info {
	char* name;
	int age;
};

int getInfo(const char* name, struct info* p){
     if(strcmp(name, "helen") == 0) {
     	p->age = 20;
     } else {
     	p->age = 0;
     }
     return 0;
}

```

**Comment by ovenpasta** [comment]
Like this?

```
(load-shared-object "./libffi.so")

(define-ftype info
     (struct
	 (name (* char))
	 (age int)))

(define strdup (foreign-procedure "strdup" (string) (* char)))
(define getInfo (foreign-procedure "getInfo" (string (* info)) int))

(define ti (make-ftype-pointer info (foreign-alloc (ftype-sizeof info))))

;; I didn't find a more direct way to do this... (yet)
(ftype-set! info (name) ti (strdup "alexander"))

(getInfo "helen" ti)

(printf "info/ age=~d\n"  (ftype-ref info (age) ti))

;; THERE SHOULD BE A BETTER WAY TO DO THIS:
(define (char*->string fptr)
  (utf8->string
   (apply bytevector
      (reverse
       (let loop ([i 0] [acc '()])
         (let ([c (char->integer (ftype-ref char () fptr i))])
           (if (zero? c)
	       acc
	       (loop (+ i 1) (cons c acc)))))))))

(printf "info/ name=~a\n"  (char*->string (ftype-ref info (name) ti)))

(define free-char* (foreign-procedure "free" ((* char)) void))
  
(free-char* (ftype-ref info (name) ti))

;; there are many ways to do this stuff, each time I find new ways :)
```

**Comment by jltaylor-us** [comment]
@netmany 
> the github seems better than google forum for exchanging ideas on scheme outer and inner mechanism discussion;
GitHub Issues are **not** an appropriate mechanism for general discussion.

**Comment by ovenpasta** [comment]
Anyway, the ftype documentation shoud have more examples... there are a lot of common situations that are not described there and could help people to introduce into it.

**Comment by akeep** [comment]
@netmany See issue #119 for information on handling strings across the foreign interface---these questions have already been answered there.

@netmany, I don't really mind answering questions here, in general, but I do agree with @ovenpasta and @jltaylor-us that the real purpose of github issues is to report potential bugs and request new features.  Sometimes, it is unclear if the problem you've encountered is a bug or a miss understanding of how to use the tool, so naturally some questions fall in to this category.

I believe the advantage of using the mailing list/google group  is that it provides an obvious archive for these types of questions, whereas, once people have their questions answered here, and close an issue, the issue is closed and it is no longer obvious that the conversation has taken place without searching the closed issues, which is possibly why you missed that handling strings has already been discussed.

Anyway, my 2 cents.  Good luck.

**Comment by netmany** [comment]
@akeep in issue #119 we only discuss part of the foreign interface about char* (pass in and out);
but we can't declare this type char* with string or u8* in ftype struct declaration; following declarations are not compiled:
```scheme
(define-ftype info
     (struct
	 (name string)
	 (age int)))

(define-ftype info
     (struct
	 (name u8*)
	 (age int)))
```
so as @ovenpasta pointed, we need the new type (* char) to declare it, but i can't find a usage reference code for it; i think int , char* and struct* are basic types which need passing though C code, not through a bytevector transformation; the final code is [https://github.com/netmany/scheme-practice/tree/master/ffi](url), after all, the issue about foreign interface can be closed.

**Comment by akeep** [comment]
@netmany The ``ftype`` stuff makes this pretty straightforward, if not necessarily as convenient as handling strings directly. Technically speaking, we handling it exactly the same way C does.  C does not have a "string" type, instead it represents strings as an array of characters (or a pointer to chunk of memory that holds an array of characters as your example does.

As far as they ``ftype`` it is a straightforward translation from your C struct:

```C
struct info {
	char* name;
	int age;
};
```

Becomes:

```racket
(define-ftype info
  (struct
    [name (* char)]
    [age int]))
```

Notice, the "string" is represented _exactly_ the same way your C struct is representing it, as a pointer to a chunk of memory containing characters.  This is what @ovenpasta was trying to indicate to you.

Now, we can write our procedure definition to make use of this:

```racket
(define getInfo (foreign-procedure "getInfo" (string (* info)) int))
```

Note the type, here, we are using ``string`` for the first argument, because it is convenient to do so and the type in your example is ``const char *`` so we know that the ``getInfo`` function will not be modifying the first argument.  The second argument is a pointer to an``info`` ftype, represented ``(* info)`` in the same way that ``(* char)`` represented a pointer to a character in the ``info`` ftype.

Of course, in your example code the ``p`` argument of ``getInfo`` is an output only argument, but we still need to allocate a pointer into memory that it can modify.

```racket
(define my-info (make-ftype-pointer info (foreign-alloc (ftype-sizeof info))))
```

In your example code, it never does anything with the ``name`` in the ``info`` struct, so it is not clear if we need to allocate space for that or not.  I've made a slightly modified version of your code that copies back a "full" name in to ``p`` argument, and the ``getInfo`` function allocates space for this (see my update to your version below).

Now we are ready to call ``getInfo``:

```racket
> (getInfo "helen" my-info)
0
```

Now ``my-info`` has information filled in.  We can access this information using the ``ftype-ref`` form:

```racket
> (ftype-ref info (age) my-info)
20
> (ftype-ref info (name 0) my-info)
#\H
```

Of course, we only accessed the first letter from the returned name.  We can convert the full string using simple recursive function:

```racket
> (let f ([i 0])
    (let ([c (ftype-ref info (name i) my-info)])
      (if (char=? c #\nul)
          (make-string i)
          (let ([str (f (fx+ i 1))])
            (string-set! str i c)
            str))))
"Helen Morris"
```

When you are done with the ``my-info`` data, don't forget that you have two chunks of foreign memory allocated, the chunk containing the C string "Helen Morris" and the ``info`` struct.  So we need to free both:

```racket
> (foreign-free (ftype-pointer-address (ftype-ref info (name) my-info)))
> (foreign-free (ftype-pointer-address my-info))
```

You can also fill in an ``info`` ftype pointer and string:

```racket
> (define my-name "Andy Keep")
> (define my-info (make-ftype-pointer info (foreign-alloc (ftype-sizeof info))))
> (ftype-set! info (name) my-info
    (foreign-alloc
      (fx* (ftype-sizeof char) (fx+ (string-length my-name) 1))))
```
Now we've got some space allocated for both the struct and the string, so we need to copy the contents of ``my-name`` into the ``char *`` pointed to by ``my-info``:

```racket
> (let loop ([i 0])
    (unless (fx= i (string-length my-name))
      (ftype-set! info (name i) my-info (string-ref my-name i))
      (loop (fx+ i 1))))
> (ftype-set! info (name (string-length my-name)) my-info #\nul)
```

Now we have our string in there, and we can read it back out using the same technique we used before.

```racket
> (let f ([i 0])
    (let ([c (ftype-ref info (name i) my-info)])
      (if (char=? c #\nul)
          (make-string i)
          (let ([str (f (fx+ i 1))])
            (string-set! str i c)
            str))))
"Andy Keep"
```

The modified code from your example that I was using i the following:

```C
// file ffi.c

#include <string.h>
#include <stdlib.h>

// test ffi arguments passing

#define max(x, y) (((x) > (y)) ? (x) : (y))

int passVal(int srcInt, int* dstInt, const char* srcStr, char* dstStr, size_t dstStrLen) {
  *dstInt = srcInt + 1;
  strncpy(dstStr, srcStr, max(dstStrLen, sizeof(srcStr)));
  return 0;
}

struct info {
  char* name;
  int age;
};

static char *helen_full_name = "Helen Morris";

int getInfo(const char* name, struct info* p){
  if(strcmp(name, "helen") == 0) {
    int full_name_len = strlen(helen_full_name);
    p->name = (char *)malloc(sizeof(char) * (full_name_len + 1));
    strncpy(p->name, helen_full_name, full_name_len);
    p->name[full_name_len] = '\0';
    p->age = 20;
  } else {
    p->name = NULL;
    p->age = 0;
  }
  return 0;
}
```

**Comment by netmany** [comment]
@akeep in the beginning we used int getInfo(const char* name, struct info* p); but the name can be contained in p; so we changed the interface to the following:
```C
int getInfo(struct info* p){
     if(strcmp(p->name, "helen") == 0) {
     	p->age = 20;
     } else {
     	p->age = 0;
     }
     return 0;
}
```
and then we need pass in name value before calling getInfo.
thanks for you example code!
