### ISSUE TITLE
Recompiling Chez Scheme after changing fields of a record

### ISSUE THREAD

**Issue by gus-massa** [cisco/ChezScheme#153]
I’m trying to add a field to the record `primref `in [s/primref.ss](https://github.com/cisco/ChezScheme/blob/master/s/primref.ss) but I get an error while compiling. I made a minimized version of my change: https://github.com/gus-massa/ChezScheme/commit/5545971fbc71016133fc6ca4f87040b276e3bb0a  /  [Tests in Travis](https://travis-ci.org/gus-massa/ChezScheme/jobs/216570350#L556).

Am I missing something obvious, like updating the definition elsewhere, or do I have to recompile the intermediate files with an especial command?

**Comment by dybvig** [comment]
You've picked one of the trickier records to update.

Often, the solution is simply to change the uid, i.e., in

```
(define-record-type primref
  (nongenerative #{primref a0xltlrcpeygsahopkplcn-2})
  (sealed #t)
  (fields name flags arity signatures))
```

change `a0xltlrcpeygsahopkplcn-2` to `a0xltlrcpeygsahopkplcn-3`.  (You might want to check first to make sure the new name isn't used elsewhere.)

This resolves the "mismatched record type" error.  In this case, however, you immediately get another problem, which is an unrecognized record error in $uncprep.

Such errors typically result from old instances floating around that code expecting new instances trips on.  They can often be resolved by using the `update-record-type` macro, which is defined in cmacros.ss.  For example:

```
(update-record-type (primref make-primref primref?) (primref-name primref-flags primref-arity primref-signatures) ()
  ; old record definition, with stub for missing accessor
  (begin
    (define-record-type primref
      (nongenerative #{primref a0xltlrcpeygsahopkplcn-2})
      (sealed #t)
      (fields name flags arity))
    (define (primref-signatures x) 'signature))
  ; new record definition, with stub for missing accessor
  (define-record-type primref
    (nongenerative #{primref a0xltlrcpeygsahopkplcn-3})
    (sealed #t)
    (fields name flags arity signatures))
)
```

In this case, however, the error results from new instances tripping up old code.  To get around this requires a bit of work, starting with building one system that understands but doesn't create instances of the new record type, using it to bootstrap a new system that understands and creates instances of the new record type, then using it to bootstrap a system that understands only the new record type.  To make life easier if you make mistakes or need to adjust your changes, you should actually bootstrap the first from one that deals only with the old record type.  (By the same token, to make life harder you can try to do all of these steps in the same workarea, and you might succeed if you get everything right the first time.)  Assuming you're on an OS X system, here's the complete process:

1. Create a fresh copy of the repository.  WARNING: if you choose not to clone a new copy, make sure your existing copy is free from any of the related changes before starting.

```
git clone <path to branch> chezscheme
cd chezscheme
```

2. Build an untouched base system for bootsrapping.

```
configure --workarea=understands-only-old
make
```

3. Next build a system that understands the new record type but doesn't create instances of it yet, using a different workarea.  WARNING: don't forget to make a local copy of the files you edit on this and the other steps.  Don't edit the root-directory copies, or you'll find it difficult to retrace your steps if you need to make changes.

```
workarea a6osx understands-new-creates-old
pushd understands-new-creates-old/s
cp ../../s/primref.ss .
edit s/primref.ss (Edit 1 below)
make -f Mf-cross m=a6osx xm=a6osx base=../../understands-only-old
(cd ../c; make)
popd
```

4. Next build a system that understands and creates instances of the new record type:

```
workarea a6osx understands-new-creates-new
pushd understands-new-creates-new/s
cp ../../s/primref.ss ../../s/primvars.ss .
edit s/primref.ss and s/primvars.ss (Edit 2 below)
make -f Mf-cross m=a6osx xm=a6osx base=../../understands-new-creates-old
(cd ../c; make)
popd
```

5. Finally build a system that understands only the new record type, bootstrapping itself at the end:

```
workarea a6osx understands-only-new
pushd understands-only-new/s
cp ../../s/primref.ss ../../s/primvars.ss .
edit s/primref.ss and s/primvars.ss (Edit 3 below)
make -f Mf-cross m=a6osx xm=a6osx base=../../understands-new-creates-new
(cd ../c; make)
make allx
popd
```

Edit 1 (primref.ss only):

The first edit replaces the existing record definition of `primref` with one that understands both old and new record types but creates old ones.  It abuses the `update-record-type` macro by swapping "old" and "new" roles, since `update-record-type` exports the new maker and we want the old.

```
(update-record-type (primref make-primref primref?) (primref-name primref-flags primref-arity primref-signatures) ()
  ; new record definition, with stub for missing accessor
  (define-record-type primref
    (nongenerative #{primref a0xltlrcpeygsahopkplcn-3})
    (sealed #t)
    (fields name flags arity signatures))
  ; old record definition, with stub for missing accessor
  (begin
    (define-record-type primref
      (nongenerative #{primref a0xltlrcpeygsahopkplcn-2})
      (sealed #t)
      (fields name flags arity))
    (define (primref-signatures x) 'signature))
)
```

Edit 2 (primref.ss and primvars.ss both):

This edit to primref.ss simply puts the `update-record-type` forms in the "proper" order:

```
(update-record-type (primref make-primref primref?) (primref-name primref-flags primref-arity primref-signatures) ()
  ; old record definition, with stub for missing accessor
  (begin
    (define-record-type primref
      (nongenerative #{primref a0xltlrcpeygsahopkplcn-2})
      (sealed #t)
      (fields name flags arity))
    (define (primref-signatures x) 'signature))
  ; new record definition, with stub for missing accessor
  (define-record-type primref
    (nongenerative #{primref a0xltlrcpeygsahopkplcn-3})
    (sealed #t)
    (fields name flags arity signatures))
)
```

For primvars.ss, make the changes you already made.

Edit 3 (primref.ss and primvars.ss both): 

This edit removes the `update-recordd-type` form leaving only the new definition in place:

```
(define-record-type primref
  (nongenerative #{primref a0xltlrcpeygsahopkplcn-3})
  (sealed #t)
  (fields name flags arity signatures))
```

For primvars.ss, again make the changes you already made.

You can start again at Step 3 if you need to modify the new record type definition.  At some point, if you want to commit and push the changes, you'll need to get the final local copies back to the root directory.  You can use `checkin understands-only-new` to do that or simply copy the files you've modified (including the boot files) into the proper root source directory.

**Comment by gus-massa** [comment]
Thanks! I have to retry a few steps because I made a mistake, but finaly this worked. https://github.com/gus-massa/ChezScheme/commit/0ba66251c32cae43f5947962ea6d67ac27bf65d0
([Tests](https://travis-ci.org/gus-massa/ChezScheme/builds/217855727)) 

Some minor details/remarks:

I had to change `a6osx` to `a6nt` everywhere, and add `./` in front of `configure` and `workarea`.

`checkin` offers to copy too many files. I selected only the `s/primref.ss`, `s/primvars.ss`, `boot/a6nt/petite.boot` and `boot/a6nt/scheme.boot`

 After this, I also run `make bootfiles` to update the other boot files.
