### ISSUE TITLE
fasl-file-equal? comparison fails (sbb petite.boot)

### ISSUE THREAD

**Issue by blessedbliss** [cisco/ChezScheme#173]
Does not prevent binary creation, the program seems to work as intended but this does not look good.
```
$ make -j2
make[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
Exception in $fasl-file-equal?: code comparison failed while comparing ../boot/ta6le/sbb and ../boot/ta6le/petite.boot within fasl entry 103
make[4]: *** [checkboot] Error 255
```

**Comment by dybvig** [comment]
I don't experience this problem with `configure --threads; make` in the current repo.  It's possible you happened to pull when the boot files were out-of-date relative to the source, which could cause this problem.

**Comment by blessedbliss** [comment]
If that is the case, boot files provided by the stable release source package (v9.4, since initial commits apparently) are outdated. The error does not seem to appear after compiling it once, having "bootfile comparison succeeded" at the end of the build, to which I assume that is because new bootfiles are compiled. The only way to reproduce that was through `make distclean; ./configure --threads; make`.
If that behaviour is expected (new bootfiles compiled for the binaries), this issue should be closed, and apologies for wasting your time. Build logs attached, number at the beginning indicates the order.

OS: CentOS 7.3.1611 x86_64
Kernel: 3.10.0-514.26.2.el7.x86_64
`gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
`
[1 - fresh compilation.txt](https://github.com/cisco/ChezScheme/files/1157236/1.-.fresh.compilation.txt)
[2 - make distclean.txt](https://github.com/cisco/ChezScheme/files/1157234/2.-.make.distclean.txt)
[3 - make clean.txt](https://github.com/cisco/ChezScheme/files/1157235/3.-.make.clean.txt)

**Comment by dybvig** [comment]
I finally understand this issue after looking through your `make distclean.txt` attachment.  Yes, this is expected behavior.

The bootstrap process generally requires two runs to produce equivalent boot files.  The first run uses the pre-compiled compiler and run-time system in the distribution boot files to compile the compiler and run-time system sources into the first set of new boot files, and the second run uses the freshly compiled compiler and run-time system in the first set of new boot files to compile the sources into the second set of new boot files.  The first set of new boot files is generally not equivalent to the boot files in the distribution, hence the (ignored) boot-file comparison exception you noticed midway through the build.  On the other hand, the second set of new boot files is usually equivalent to the first set of new boot files, hence the overall success of the build.

The boot files in the distribution are produced via a cross-compiler.  The cross compiler is compiled with different compiler options that can result in evaluation order differences within the compiler that in turn result in harmless differences in code layout within the boot files.  When the host and target machines differ, the cross-compiler also produces larger and less efficient code due to the disabling of some machine-dependent optimizations.  This is why the first set of new boot files are generally not equivalent to the boot files in the distribution.
