### ISSUE TITLE
Printing black holes

### ISSUE THREAD

**Issue by gus-massa** [cisco/ChezScheme#186]
When I try

    (display '#0=#0#)

the program pauses indefinitely, until I hit `^C`. (It's probably in an infinite loop.)

Is this the official behavior? It would be nice to have a special token to show it, like `#!eof`, `#!bwp` or `#!base-rtd`. Something like `#!bh`.

**Comment by akeep** [comment]
Hey @gus-massa,

This is the expected behavior.  Chez Scheme provides two methods for writing scheme objects: ``write`` and ``display``.  The pertinent difference for your example, is that ``write`` recognizes recursive objects and allows them to be printed using graph notation (as you used in your black hole specification) and while ``display`` does not.  Similarly in ``format``, ``~s`` produces the same output as ``write`` while ``~a`` produces the same output as ``display`` (or fails to terminate as you've observed).

```
> (write '#0=#0#)
Warning in write: cycle detected; proceeding with (print-graph #t)
#0=#0#
> (print-graph #t)
> (write '#0=#0#)
#0=#0#
> (display '#0=#0#)  ; => never terminates!
^Cbreak> q
```

Or with ``printf``:

```
> (printf "black hole: ~s~%" '#0=#0#)
black hole: 
Warning in write: cycle detected; proceeding with (print-graph #t)
#0=#0#
> (print-graph #t)
> (printf "black hole: ~s~%" '#0=#0#)
black hole: #0=#0#
> (printf "black hole: ~a~%" '#0=#0#)
^Cbreak> q
```

**Comment by gus-massa** [comment]
I was using `display `for debugging and I hit an unexpected black hole. Next time I'll use `write `instead. Thanks
