### ISSUE TITLE
Chez/Armor test suite error: Exception: invalid memory reference.  Some debugging context lost

### ISSUE THREAD

**Issue by marcomaggi** [cisco/ChezScheme#196]
This is just a preliminary report, because I do not know when I will have time and will to inspect this more deeply.  On my x86_64-slackware-linux-gnu, when running the test suite of the package [Chez/Armor](https://github.com/marcomaggi/ChezArmor), two tests fail with the following:

```
Exception: invalid memory reference.  Some debugging context lost
```

as you can see also at the Travis [page](https://travis-ci.org/marcomaggi/ChezArmor/jobs/263119507).

Notice that I install Chez Scheme using `chez` as name of the main executable, rather than `scheme`; so to use the makefile you can do:

```
make CHEZ_PROGRAM=scheme check
```

it should word with `configure` too (not tested, though) or just create a script named `chez` that executes `scheme`.

**Comment by marcomaggi** [comment]
This happens with Chez Scheme commit `996ba3897f1c4ea27b4b6a15264dc6f6a14c6cdb`.

From the top source directory of the package I see this:

```
$petite-chez --libdirs lib:tests tests/test-armor-base32.sps
Petite Chez Scheme Version 9.4.1
Copyright 1984-2017 Cisco Systems, Inc.

*** testing ASCII armor base32
Exception: attempt to apply non-procedure 12
```

and also this:

```
$petite-chez --libdirs lib:tests tests/test-armor-base64.sps
Petite Chez Scheme Version 9.4.1
Copyright 1984-2017 Cisco Systems, Inc.

*** testing ASCII armor base64
Exception: attempt to apply non-procedure 18
```

**Comment by akeep** [comment]
Hey @marcomaggi 

There is a bug in your ``receive-and-return`` macro in ``lib/armor/helper.sls`` that starts on line 96.  The way the macro is written, you will end up attempting to call the values returned by the ``call-with-values`` your macro expands into:

```scheme
(define-syntax receive-and-return
  (syntax-rules ()
    ((_ ?formals ?expression ?form0 ?form ...)
     (call-with-values
         (lambda () ?expression)
       (lambda ?formals
         ?form0 ?form ...
         (apply values ?formals))))))
```

You are matching ``?formals``, which you expect to be a list, as in the ``lib/armor/base32.sls`` file on line 888, which was causing the problem on the base32 test:

```scheme
                (receive-and-return (byte)
                    (vector-ref table char)
                  (if byte
                      (incr! j)
                    (%error-invalid-input-byte char)))
```

This expands into:

```scheme
(call-with-values
  (lambda () (vector-ref table char))
  (lambda (byte)
    (if byte
        (incr! j)
        (%error-invalid-input-byte char))
    (apply values (byte)))) ;; => this is where things go wrong, because it attempts to call byte
```

Instead of ``(apply values ?formals)`` you can do something like: ``(values . ?formals)`` that will instead expand into:

```scheme
(call-with-values
  (lambda () (vector-ref table char))
  (lambda (byte)
    (if byte
        (incr! j)
        (%error-invalid-input-byte char))
    (values byte))) ;; => this is where things go wrong, because it attempts to call byte
```

And it will work for any proper list of formals.  Alternatively, you could explicitly match the formals as ``(?formals ...)`` and then use ``(values ?formals ...)``, to make it a little more obvious this is a restriction.  If you want to support the full range of formals you can match on ``(?formals ... . ?rest)`` which will match formals of ``x``, ``(x y)``, and ``(x . y)``, then you could ``(apply values ?formals ... ?rest)``

At any rate, I made the simple change and it cleared up the error for me.

**Comment by marcomaggi** [comment]
You are right.  The error `invalid memory reference` looked to me like something from the deep that should not happen as a consequence of a programming error; but I am simply not used to Chez's errors.  Sorry for the noise.

**Comment by akeep** [comment]
No problem.  Just to be clear, the invalid memory error was because you
were running in “unsafe mode” (optimize-level 3) which doesn’t do any type
checking, so when your code inadvertently tried to apply an integer, you
got an invalid memory reference.  It is a good idea to change the
optimization level to 2 to go back to safe mode, where the types will be
checked, and you should get a better error message (I was actually able to
pinpoint it pretty quickly by going into the debugger, inspecting the
continuation, and having it print the fill position the error occurred at.)
 It doesn’t always work, but it is a good starting point.

Good luck!
-andy:)

On August 10, 2017 at 11:14:29 PM, Marco Maggi (notifications@github.com)
wrote:

You are right. The error invalid memory reference looked to me like
something from the deep that should not happen as a consequence of a
programming error; but I am simply not used to Chez's errors. Sorry for the
noise.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/cisco/ChezScheme/issues/196#issuecomment-321723888>,
or mute
the thread
