### ISSUE TITLE
request: add special bytevector constructor for binary data buffers

### ISSUE THREAD

**Issue by marcomaggi** [cisco/ChezScheme#200]
I assume (without studying the code) that Chez's garbage collector does not move "big" objects that use more than one memory page; this leads to some memory being wasted by "big" objects.  So if the whole area a bytevector consumes is exactly one memory page: this object will receive no special treatment and no memory will be wasted.

Now, we specify the size of a bytevector by selecting the number of bytes in its data area; we cannot take into account the size of the bytevector's meta data.

Is it possible to add a new bytevector constructor, of unspecified byte size, whose whole memory area will fill exactly a single memory page?  I would find it useful to use such bytevectors as input/output buffers in various applications.

**Comment by dybvig** [comment]
It shouldn't move big objects, but it does.  It's been in the design for decades, but it's never been implemented.

**Comment by marcomaggi** [comment]
Got it.  Then, which is the memory layout for bytevectors?  Is there documentation for it?  Is it like [this one](http://marcomaggi.github.io/docs/vicare-scheme.html/objects-bytevectors.html)?

**Comment by akeep** [comment]
We do not have this documented, in part, because this is internal to the system and might change from version to version.

That said, scheme objects in Chez Scheme, generally fall into three categories: immediates, simple heap allocated objects, and typed heap allocated objects.  We use the bottom few bits of an object to indicate its type.  In the case of immediates, like fixnums, booleans, chars, etc. there is no allocation in the heap for the object, it is simply represented in a single machine word.  In the case of simple heap allocated objects, like pairs, flonums, and symbols, the type tag indicates the type and the size of the heap allocated object is known from the type.  Typed objects, like vectors, byte vectors, and records, use a combination of the type tag and the first word of the object to store both the type information and the metadata about the object.

Heap allocated objects are always 64-bit aligned, so there may also be some additional padding at the end.  For instance, if you are on a 32-bit machine, and you have a two-element vector it will take up a total of four 32-bit words, one word for the type/vector length, two words for the elements, and one word for padding.  A three-element vector will also take up a total of four 32-bit words, one word for the type/vector length, three words for the elements, and no padding.

So, typed objects are basically:

```
+---------------+----------+-----------------------------+
| type/metadata | data ... | <optional padding>          |
| one word      | variable | padding to 64-bit alignment |
+---------------+----------+-----------------------------+
```

To maximize the size within a page you should subtract the number of bytes in the machine word from the page size and allocate based on that.

**Comment by marcomaggi** [comment]
Fine, this is similar to what Ikarus (and so Vicare) uses; I get it.  To keep internal details internal, it makes sense to have the special constructor I want as a built-in command.  For input/output buffers I would like to allocate bytevectors whose memory layout is a full memory page (let's say 4096 bytes), including the meta data and wasting no padding.
