### ISSUE TITLE
Is the behaviour of CASE with arrow documented?

### ISSUE THREAD

**Issue by marcomaggi** [cisco/ChezScheme#207]
I see that the following happens:

```scheme
(case 2 ((1 2 3) => (lambda (x) x)))
=> (2 3)
```

but I cannot find documentation of this behaviour.  In case it is non-definitive behaviour, I would prefer:

```scheme
(case 2 ((1 2 3) => (lambda (x) x)))
=> 2
```

and also `=>` supported in the `else` clause, too.

**Comment by akeep** [comment]
Actually,``=>`` working in ``case`` is an (at least in part) an accident of implementation.  ``case`` (roughly speaking) expands into ``cond`` without processing the expressions in the ``case`` clauses.

So, in your example:

```scheme
(case 2
  ((1 2 3) => (lambda (x) x)))
```

expand (roughly) into

```scheme
(let ((t 2))
  (cond
    ((member t '(1 2 3)) => (lambda (x) x))))
```

The ``=>`` in ``cond`` is really there to bind the output of the condition expression (this is why it is not supported in the ``else`` clause of ``cond``, since there is no computation result in the else clause).  You can always bind the value going into the ``case`` in a variable if you want to reference it, or even build yourself a macro (say ``let-case`` that binds the expression compared in the ``case`` expression).

**Comment by marcomaggi** [comment]
Do you mean that there is no optimisation of `case` at all?

**Comment by akeep** [comment]
Well, ``case`` can expand into ``exclusive-cond``, which takes advantage of the profile driven optimization described in [Profile-guided meta-programming by Bowman et. al.](http://dl.acm.org/citation.cfm?id=2737990&CFID=804364471&CFTOKEN=32845307).

Additionally, ``cp0`` can optimize the ``if`` forms that eventually result from the expansion of ``cond`` into ``if``.

If you are ever curious, you can see what the expander produced using ``expand`` and what the source optimizer (``cp0``) produced using ``expand/optimize``.  In the case of your example:

```scheme
> (expand '(case 2 [(1 2 3) => (lambda (x) x)]))
(let ([#:t 2])
  (let ([#:t (#2%member #:t '(1 2 3))])
    (if #:t
        ((let ([#:p (lambda (#:x) #:x)]) #:p) #:t)
        (#2%void))))
```

You can see this expands into ``let`` and ``if`` expressions, and then the optimizer runs on it:

```scheme
> (expand/optimize '(case 2 [(1 2 3) => (lambda (x) x)]))
'(2 3)
```

And produces the result you saw when you were testing this.

So, there is no special optimizations for ``case``, but it isn't really necessary.

**Comment by marcomaggi** [comment]
Fine.  In case someone finds it interesting I have put in [this gist](https://gist.github.com/marcomaggi/025a7a410fa917e790b4316f55d9119d) an implementation of `case` which supports arrows and uses some optimisation as described in the referenced Clinger's paper.

**Comment by dybvig** [comment]
I'm reopening this issue, since `=>` being caught this way by the expansion of `case` is actually a bug.

**Comment by dybvig** [comment]
@marcomaggi, the calls to `member` are often optimized by the compiler into calls to `eq?` or `eqv?`, which is the primary way in which `case` is effectively optimized.

**Comment by dybvig** [comment]
Okay, the issue has been fixed with [this commit](https://github.com/cisco/ChezScheme/commit/303921d8515b101c558a056dcf9c05f7cad97f4a).
