### ISSUE TITLE
#e1@1 returns inexact result

### ISSUE THREAD

**Issue by leppie** [cisco/ChezScheme#21]
Returns `0.5403023058681398+0.8414709848078965i` instead of 
`1216652631687587/2251799813685248+3789648413623927/4503599627370496i`

First detected on Windows with 8.4, and retested on Linux with 9.4.

**Comment by dybvig** [comment]
You're right that `#e1@1` (and even `1@1` without the `#e` prefix) should not return an inexact number; the question is what it should return, since Chez Scheme doesn't have a representation for exact `1@1`.  There appear to be three choices, none of them ideal: (1) return `(make-polar 1.0 1.0)`, which is what we presently do, (2) return `(exact (make-polar 1.0 1.0))`, which is what you suggest, or (3) raise an exception with condition type implementation restriction.  (1) is incorrect, since the result isn't exact.  (2) is incorrect, since (exact (make-polar 1.0 1.0)) is not exactly `1@1`.  (3) is correct but probably unfriendly.

**Comment by leppie** [comment]
While 2 is incorrect, it is as good as the floating point representation.

**Comment by dybvig** [comment]
(1) has the advantage of marking the inexact representation of `1@1` explicitly as such, but (3) is the only legitimate option.

**Comment by dybvig** [comment]
My latest commit treats 1@1 as inexact and #e1@1 as violating an implementation exception.
