### ISSUE TITLE
request: support library name/reference (srfi :0) conversion to safe file pathname

### ISSUE THREAD

**Issue by marcomaggi** [cisco/ChezScheme#211]
Is it possible to add support for translating a library name/reference like `(srfi :0)` to a safe pathname stem like `srfi/%3a0`, like other implementations do?

It is a matter of using code like the following to translate symbols in the library name into directory pathname components:

```scheme
#!r6rs
(import (rnrs (6))
  (only (chezscheme) pretty-print))

(define (%compose-stem id*)
  (define (%display-hex N port)
    (if (fx<=? 0 N 9)
	(display N port)
      (write-char (integer->char (fx+ (char->integer #\a) (fx- N 10))) port)))
  (let-values
      (((port extract) (open-string-output-port)))
    (let next-component ((id  (car id*))
			 (id* (cdr id*)))
      (write-char #\/ port)
      (for-each (lambda (N)
		  ;;Only characters in the ranges [#\a, #\z], [#\A, #\Z], [#\0, #\9],
		  ;;plus  #\- are  left untouched;  everything else  is encoded  in a
		  ;;percent sequence.
		  (if (or (fx<=? (char->integer #\a) N (char->integer #\z))
			  (fx<=? (char->integer #\A) N (char->integer #\Z))
			  (fx<=? (char->integer #\0) N (char->integer #\9))
			  (fx=?  N (char->integer #\-)))
		      (write-char (integer->char N) port)
		    (let-values
			(((D M) (div-and-mod N 16)))
		      (write-char #\% port)
		      (%display-hex D port)
		      (%display-hex M port))))
	(bytevector->u8-list (string->utf8 (symbol->string id))))
      (if (pair? id*)
	  (next-component (car id*) (cdr id*))
	(extract)))))

(pretty-print (%compose-stem '(srfi :1 lists))
	      (current-error-port))

(pretty-print (%compose-stem '(A./_+%Z<>$!?^*))
	      (current-error-port))
```

**Comment by akeep** [comment]
Yes, it is unfortunate that ``:`` was chosen as a way to do this, since some file systems seem to have trouble with ``:``.  It is worth noting that most modern file systems allow ``:`` in file names.  Windows seems to be the hold out, although the [Windows Filesystem Character Set](https://msdn.microsoft.com/en-us/library/windows/desktop/dd317748%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) page does not list ``:`` as a restriction, in testing it seems the DOS command shell does restrict this, though the cygwin and bash interfaces support it.

All of that said, I'm not a huge fan of the solution you've outlined here.  Part of the problem is that it makes assumptions about the underlying file system that are overly restrictive in almost every case.  Unicode characters, including spaces, punctuation, etc. are allowed on many operating systems and a translation that restricts to the character ranges ``a-z``, ``A-Z``, ``0-9``, and ``-`` seems extremely overly restrictive.  Especially considering ``_`` is also a commonly used file name element.

One possible solution is to expose a hook to how the file name is generated from the path to allow people to decide how restrictive they want the file system translation to be.

Right now that library search is already a fairly complicated processes since it looks through the cartesian product of the library directories and extensions, and searches for matching pairs of source and binary libraries, optionally recompiling libraries if the source code of the library (or it's dependencies) has changed since the last time the library was compiled.

I'd have to think some about how this would plug in to the system and how this should be exposed.

**Comment by marcomaggi** [comment]
The `:` in file pathnames is also troublesome in Makefiles, where it must be quoted with a backslash; the same goes for command line completion in some Unix shells.  I will try to port my SRFI collection to Chez using quoted `:` in Makefiles and see how it feels.

Writing build scripts with alphanumeric file pathnames only is for sure easier.  Is this a matter of priority?  Do we favour build scripts comfortability or of file names expressiveness?  We need to remember that only developers (not end users) need to look at file names in 99% of cases.
