### ISSUE TITLE
function local variable can't be inspected in debugger when exception occured

### ISSUE THREAD

**Issue by netmany** [cisco/ChezScheme#215]
when input a wrong parameter "a" to x of function f, the x can't be inspected in debugger (r x).
and in nested function call, we also can't inspect function parameter in debugger.
how to deal with it?
`
> (define f (lambda (x) (+ 1 x)))
> (f "a")
Exception in +: "a" is not a number
Type (debug) to enter the debugger.
> (debug)
debug> i 
system continuation in new-cafe                              : sf
  0: system continuation in new-cafe
system continuation in new-cafe                              : s
  continuation:          null continuation
  frame and free variables:
  0: system continuation in dynamic-wind

`

**Comment by akeep** [comment]
The debugger is actually an inspector of the current continuation (effectively the chain of stack frames for the non-tail calls leading to the failure) from where the failure occurred.  This means that local variables that are still in scope will be visible in the debugger (since they are part of the continuation).  In your example there is only a tail call, so the current continuation does not contain a local variable.

In cases where you are debugging a compiled file (as opposed to at the REPL), you can also ask the debugger to print out a file location which can help to identify where the error occurred, and what variable might be involved.

**Comment by netmany** [comment]
@akeep how to construct a helper function (g x) which non-tail call (f x) for debugging purpose?

**Comment by akeep** [comment]
In general you cannot construct a helper function that ensures a local variable is on the stack for an arbitrary function when an exception occurs.

In your example, the function being called does not have a stack on the frame, since it is at the tail of the computation.  You can force a frame to be created by capturing the current continuation with ``call/cc``, and you can even use this with the inspector to look at the current continuation.  (In fact this is how the debugger works, it allows you to walk the continuation.)

Starting from your example you could do something like:

```
> (define f (lambda (x) (call/cc (lambda (k) (inspect k))) (+ 1 x)))
> (f "a")
#<continuation in f>                                              : s
  continuation:          #<system continuation in new-cafe>
  procedure code:        (lambda (x) (call/cc (lambda (...) (...))) (+ 1 x))
  call code:             (call/cc (lambda (k) (inspect k)))
  frame and free variables:
  0. x:                  "a"
#<continuation in f>                                              : q

Exception in +: "a" is not a number
Type (debug) to enter the debugger.
```

Now you can see that ``x`` is on the frame.  It is worth noting that if ``x`` was not referenced after the ``call/cc`` expression in the code, it would not be represented there, because it would not be needed across the non-tail call.

You can also inspect the variable value directly, by simply passing it to inspect:

```
> (define f (lambda (x) (inspect x) (+ 1 x)))
> (f "a")
"a"                                                               : q

Exception in +: "a" is not a number
Type (debug) to enter the debugger.
```

Sometimes it can be helpful to generate a pair with name:

```
> (define f (lambda (x) (inspect (cons 'x x)) (+ 1 x)))
> (f "a")
(x . "a")                                                         : s
  car:                   x
  cdr:                   "a"
(x . "a")                                                         : q

Exception in +: "a" is not a number
Type (debug) to enter the debugger.
```

Hope that helps!
