### ISSUE TITLE
Threaded version of Chez fails to build with glibc 2.26

### ISSUE THREAD

**Issue by lyu** [cisco/ChezScheme#220]
Glibc 2.26 has moved `xlocale.h` to `bits/types/__locale_t.h`, see [upstream commit](https://sourceware.org/git/?p=glibc.git;a=commit;h=f0be25b6336db7492e47d2e8e72eb8af53b5506d). Currently the threaded version of Chez fails to build on Linux systems that use this new release of glibc. The header file is included in `expeditor.c`.

**Comment by dybvig** [comment]
Can you try just removing the include of `xlocale.h`?  That is, don't replace it with an include of `bits/types/__locale_t.h`? 

If that works, we might be able to include `xlocale.h` only when `__GLIBC__` is not defined and have it work both with the newer and older versions of glibc, since it looks like earlier versions of glibc `locale.h` include `xlocale.h`.

**Comment by lyu** [comment]
Removing `xlocale.h` works, the code compiles and the tests seem to pass. Also, `locale.h` of glibc 2.26 includes `bits/types/locale_t.h`, which in turn includes `bits/types/__locale_t.h`, so yes, everything is still in there.

**Comment by dybvig** [comment]
Okay, [this commit](https://github.com/cisco/ChezScheme/commit/b04e9123a427034a39fc9084ba2a8b04608bbb3b) ifdef's out the offending include for glibc.
