### ISSUE TITLE
Avoid installation of Petite Chez and scheme-script

### ISSUE THREAD

**Issue by marcomaggi** [cisco/ChezScheme#221]
As far as I can tell there is no way to disable installation of Petite Chez and `scheme-script`.  I would appreciate it through a `configure` option.

(By the way: does it still make sense to build and install Petite Chez?)

**Comment by akeep** [comment]
This is true, but ``petite`` and ``scheme-script`` are just hard links to ``scheme`` that cause it to operate in slightly different modes.

When ``scheme`` detects that it has been run as ``scheme-script`` it uses the first command line argument to determine the scheme script to run and makes all other command line arguments available to the script through the ``(command-line)`` and ``(command-line-arguments)``.   ``scheme-script`` is equivalent to ``scheme --program`` and command line arguments intended for the use in the scheme script can also be passed after ``--``, though this is not needed when using ``--program``.

In the case of ``petite``, the ``scheme`` executable decides on which boot file(s) to attempt to load based on the name the executable was run as (unless the boot files are explicitly specified with the ``-b`` command line argument.  Normally, we build two boot files: ``petite.boot`` and ``scheme.boot``.  ``petite.boot`` contains all of the basic scheme libraries and REPL support, including the expression editor.  ``scheme.boot`` contains the scheme compiler.  When the executable name is ``scheme`` it attempts to load the ``scheme.boot`` file, which lists the ``petite.boot`` as a dependency.  When the executable is ``petite`` it loads the ``petite.boot`` only.

Petite Chez is still useful because it allows for a smaller memory footprint when running scheme programs, and can be used a smaller run time for a precompiled scheme program.

**Comment by marcomaggi** [comment]
> and can be used a smaller run time for a precompiled scheme program.

I was not aware of this.  I will have to meditate more on this.
