### ISSUE TITLE
Cannot read shared library

### ISSUE THREAD

**Issue by ta2gch** [cisco/ChezScheme#235]
This is a related issue for #234 .
[This code (Gist)](https://gist.github.com/ta2gch/143025132b8753779ffbbb10406dce51) will calls a C++ function. When I typed `make test` to run this code, I got **sometimes** the message;

```
Exception in read: character  in symbol syntax is not allowed in #!r6rs mode at line 1, char 2 of regex.so
```

Please give me your help. Thank you.

## Environment
- macOS
- Chez Scheme v9.5
- Clang 900.0.38 (g++ is a symbolic link to clang++ in macOS)

**Comment by akeep** [comment]
@ta2gch

You are running into a name clashing problem here.  Back when Kent started the Chez Scheme project he decided to use the file extensions `.ss` for Scheme Source and `.so` for Scheme Object (where the `.so` file is the result of compiling a `.ss` file with `compile-file`, `compile-library`, or `compile-program`.

Unfortunately, when some Unix systems decided to add dynamically loadable object files they also decided to use the name `.so` for Shared Object.  It is worth noting that this not the extension the macOS uses, it uses the extension `.dylib` (or Dynamic Library) for this purpose, though it is not restricted to this.

What is happening in this case is that when you've compiled the `regex.c` file to `regex.so` and then you load up Chez Scheme, and import the `(regex)` library, Chez Scheme sees that there is a `regex.so` file, assuming it is the Scheme Object file and attempting to load it, thinking you had compiled `regex.ss` to `regex.so`.

In this case, since you are on a macOS machine, I'd suggest using the standard macOS extension: `.dylib` instead, and you'll avoid the problem entirely.

That said, the other options are to name your `.so` file differently (say `libregex.so`) or to change scheme library extensions by setting the ``library-extensions`` parameter or by using the ``--libexts`` command line extension.  For instance, you could use the extension `.scheme-object` for scheme object files and either set the parameter:

```scheme
% scheme
Chez Scheme Version 9.4.1
Copyright 1984-2016 Cisco Systems, Inc.

> (library-directories (map (lambda (p) (cons (car p) ".scheme-object")) (library-directories)))
> (import (regex))
> (display (regex-replace-all "foo" "o" "i"))
fii
```

or us the command line option:

```scheme
% scheme --libexts .sls::.scheme-object
Chez Scheme Version 9.4.1
Copyright 1984-2016 Cisco Systems, Inc.

> (import (regex))
> (display (regex-replace-all "foo" "o" "i"))
fii
```

Note that the ``library-directories`` parameter is stored as a list of source-name, object-name pairs, with the following defaults:

```scheme
% scheme
Chez Scheme Version 9.4.1
Copyright 1984-2016 Cisco Systems, Inc.

> (library-extensions)
((".chezscheme.sls" . ".chezscheme.so")
  (".ss" . ".so")
  (".sls" . ".so")
  (".scm" . ".so")
  (".sch" . ".so"))
```

**Comment by ta2gch** [comment]
I got the he reason of this issue. There are two files having the same name "regex.so".
And there are three solution;

1. Changing the prefix of shared library like "regex.dylib" in macOS.
2. Renaming "regex.cpp" to "libregex.cpp"
3. Chnaging the prefix of scheme object with `--libexts`or `library-extensions`

Thank you for your help and great suggests.
