### ISSUE TITLE
can't import two different version of one same library

### ISSUE THREAD

**Issue by guenchi** [cisco/ChezScheme#251]
we start a project : A Package Manager for Chez Scheme, it can easily download, initial the Scheme library, and automatelly compile c library.

GitHub: https://github.com/guenchi/Raven
Officiel Web Site: http://ravensc.com

And there is the problem : 

if the current project depends lib A and lib B
and lib A depends lib C 1.1.0, lib B depends lib C 2.1.0
we can't import two different version of one same library in a same project

**Comment by jltaylor-us** [comment]
As was [posted](https://groups.google.com/forum/#!topic/chez-scheme/X6z1coCurj8) in the chez-scheme google group less than a week ago, this is expected behavior for an r6rs compliant scheme implementation.

> Graham Watt | Dec 24
You cannot import two libraries with different versions into the same runtime. See this for info: http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-10.html#node_idx_268
> 
> The relevant sentence is:
>> To avoid problems such as incompatible types and replicated state, implementations should prohibit the two libraries whose library names consist of the same sequence of identifiers but whose versions do not match to co-exist in the same program.

That said, the r6rs spec says "should" not "must", so it may be possible to come up with some semantics that make sense and allow multiple versions of a library to coexist in one runtime.  Seems like a lot of opportunity for unexpected behavior, though.  Perhaps one of the maintainers will chime in.

**Comment by akeep** [comment]
Just to follow up on what @jltaylor-us mentioned, there are a couple of challenges with having multiple versions of the same library loaded.

First, different versions of the same library might use different underlying representations for the data they operate on (in fact, different compilation instances of the same version of the library may also have this property).  If the two libraries are completely isolated, that might be okay, however if data created by one version of the library can flow to the other version of the library, the program will have unexpected errors.

Second, a library might expect that its state is unique, either because it connects to an external resource that it expects to have the only handle on, or because it is maintaining internal state to ensure uniqueness of data produced by the library.  In both cases, loading multiple versions of the library would result in multiple versions of this state being loaded, which also has the potential to cause unexpected errors in the final program.

In both of these cases the errors are likely to be the kind that are not immediately obvious to someone using the the library or program that results in multiple versions of the same library being loaded.

So it is a bit conservative, but I suspect this was some of the reasoning behind the R6RS prohibition on loading multiple versions of the same library.
