### ISSUE TITLE
Getting a pointer into a bytevector for passing to a foreign-procedure

### ISSUE THREAD

**Issue by ecraven** [cisco/ChezScheme#257]
When wrapping things that write into buffers (like =recv= and =send=), it would be nice to have a way to say "write into the bytevector at this index". Is there any way to get the pointer that the =u8*= specification would pass to the function? Then I could just add the relevant offset to it myself.

**Comment by burgerrg** [comment]
If you're using a foreign function, pass the bytevector as `u8*` and the index as `size_t` and do the pointer addition in the foreign code. See https://cisco.github.io/ChezScheme/csug9.5/foreign.html#./foreign:s8 for details:

> u8*: The argument must be a Scheme bytevector or #f. For #f, the null pointer (0) is passed to the foreign procedure. For a bytevector, a pointer to the first byte of the bytevector's data is passed. If the C routine to which the data is passed requires the input to be null-terminated, a null (0) byte must be included explicitly in the bytevector. The bytevector should not be retained in foreign variables or data structures, since the memory management system may relocate or discard them between foreign procedure calls, and use their storage for some other purpose.

**Comment by ecraven** [comment]
Ideally I'd like to not have to write C code (that would mean I cannot deploy the Scheme code without also having a C compiler). recv and send are standard C networking functions, I'd prefer not having to wrap them just for some pointer arithmetic.. is the problem that the bytevector might be moved around by the GC while I'm trying to calculate the correct addresses in Scheme code?

**Comment by burgerrg** [comment]
Yes, you can get the address in Scheme, but you'll need to either lock the bytevector before getting its address or enter a critical section so that the garbage collector won't move the bytevector at the wrong time.

If you go with the C wrapper approach, you would compile the wrapper on your machine and distribute the shared library. The target machine won't need a C compiler. See https://github.com/becls/swish for an example of a wrapper and C code that locks scheme objects when it stores their addresses and unlocks them when it's finished.

**Comment by ecraven** [comment]
> Yes, you can get the address in Scheme, but you'll need to either lock
> the bytevector before getting its address or enter a critical section
> so that the garbage collector won't move the bytevector at the wrong
> time. 
> If you go with the C wrapper approach, you would compile the wrapper
> on your machine and distribute the shared library. The target machine
> won't need a C compiler. See https://github.com/becls/swish for an
> example of a wrapper and C code that locks scheme objects when it
> stores their addresses and unlocks them when it's finished. 

Can all that be done from inside Scheme, without C? What functions am I
looking for to lock down objects and to get the bytevectors address?

Thanks for any help with this!

**Comment by burgerrg** [comment]
`lock-object` and `unlock-object` are described [here](https://cisco.github.io/ChezScheme/csug9.5/smgmt.html#./smgmt:s30).

To get the address, you'll need an undocumented procedure, `$object-address`, and knowledge of how bytevectors are represented. The code below disables interrupts (and hence garbage collection), determines the address of bytevector `bv` at 0-based index `index` and passes it to `f`. It doesn't do type or bounds checking.

`(with-interrupts-disabled (f (#%$object-address bv (+ (foreign-sizeof 'ptr) 1 index)))`

**Comment by burgerrg** [comment]
The C wrapper option is supported without the use of undocumented system procedures and may not even need to lock the bytevector, so I recommend the C wrapper.

**Comment by akeep** [comment]
Another approach to this is to use the foreign data facilities described in [Section 4.5 Foreign Data](http://cisco.github.io/ChezScheme/csug9.5/foreign.html#./foreign:h5) of the Chez Scheme users guide.  This is actually the standard way to communicate data back and forth with foreign procedures.  

Because allocation occurs outside the Scheme heap, you no longer need to lock and unlock it, though you are responsible for freeing it.  One way to employ the garbage collector to help with that is to use an ``ftype-pointer`` object to wrap the pointer and then put a guardian on the ``ftype-pointer`` object, and when the guardian indicates the ``ftype-pointer`` object would be freed, free the corresponding foreign data.

**Comment by ecraven** [comment]
@burgerrg: thank you, that looks exactly what I had in mind!
@akeep: how would I use them to allocate a bytevector that C cod can write into? I can only use it to allocate an array, which I still have to convert to a Scheme object if I want to easily access it, right?

**Comment by akeep** [comment]
The "array" you are allocating is effectively just a byte array, and you can access it similar to the way you access the bytevector.  The ``foreign-ref`` and ``foreign-set!`` provide you the same sort of access you have with the various bytevector ref and set! procedures.  You could also copy the foreign data into a bytevector if that is what you wanted to do.

**Comment by ecraven** [comment]
Thanks for clarifying this! @burgerrg I've used your suggestions, things seem to work fine so far ;) Thanks to both of you for helping me with this!
