### ISSUE TITLE
Predicates for ftypes

### ISSUE THREAD

**Issue by ecraven** [cisco/ChezScheme#274]
Is there a way to check which exact ftype a pointer is?
Chez errors out if I pass an incorrect ftype pointer, but I cannot find a way to access the actual *name* of the ftype. `ftype-pointer-ftype` only returns the definition, so there's no way to differentiate between to identical structs.
The record type of ftype pointers (`ftd`) seems to have no fields that I could inspect :-/

**Comment by akeep** [comment]
ftype pointers are records, so you can actually use the regular record inspection tools to look at these.

```
> (define-ftype foo (struct [a int] [b int]))
> (define-ftype foo_t (struct [a int] [b int]))
> (define foo (make-ftype-pointer foo_t 0))
> (record-rtd foo)
#<ftd foo_t>
> (record-type-name (record-rtd foo))
foo_t
```

Part of the reason the ``ftype-pointer-ftype`` returns the structure instead of the name is that not all ``ftype-pointer`` types have names.  For instance, we can create an ``ftype-pointer`` that is a pointer into an ``ftype-pointer``.

```
> (define-ftype foo_t (struct [a int] [s1 (struct [b int] [c int])]))
> (define foo (make-ftype-pointer foo_t (foreign-alloc (ftype-sizeof foo_t))))
> (ftype-set! foo_t (a) foo 1)
> (ftype-set! foo_t (s1 b) foo 2)
> (ftype-set! foo_t (s1 c) foo 3)
> (ftype-pointer->sexpr foo)
(struct [a 1] [s1 (struct [b 2] [c 3])])
> (define foo-part (ftype-&ref foo_t (s1) foo))
> (ftype-pointer-ftype foo-part)
(struct [b int] [c int])
> (record? foo-part)
#t
> (record-rtd foo-part)
#<ftd struct>
> (record-type-name (record-rtd foo-part))
struct
```

**Comment by ecraven** [comment]
Perfect, thanks a lot for elucidating me on this ;)
