### ISSUE TITLE
`Error: invalid context for definition` caused by `record-writer`

### ISSUE THREAD

**Issue by nulldatamap** [cisco/ChezScheme#291]
The following code:
```scheme
(library (bug)
  (export)
  (import (chezscheme))

  (define-record-type test)

  (record-writer (type-descriptor test)
                 (lambda (r p wr) #f))

  (define (fails-here) #f))
```
Causes the error message: `Exception: invalid context for definition (define (fails-here) #f) at line 11, char 3 of bug.ss`.
This error occurred on version `9.5` target `a6nt`.
If the `record-writer` is the last thing in the library it doesn't cause an error message, and if the code is toplevel it doesn't happen either.

The following code gives a different error message that seems to leak some implementation information that might be useful:
```scheme
(library (bug)
  (export)
  (import (chezscheme))

  (define-record-type test-a)

  (record-writer (type-descriptor test-a)
                 (lambda (r p wr) #f))

  (define-record-type test-b)

  (record-writer (type-descriptor test-b)
                 (lambda (r p wr) #f))

  (define (fails-here) #f))
```
Error message:
`Exception: invalid context for definition (define rtd ($make-record-type-descriptor #!base-rtd (quote test-b) #f (quote #f) #f ...))`

**Comment by akeep** [comment]
In both cases this is not allowed because R6RS dictates that a library is:

> A library definition must have the following form:
> 
> ```
> (library <library name>
>   (export <export spec> ...)
>   (import <import spec> ...)
>   <library body>)
> ```

and continues to say that:

> A <library body> is like a <body> (see section 11.3) except that a <library body>s need not include any expressions. It must have the following form:
> 
> ```
> <definition> ... <expression> ...
> ```
> When begin, let-syntax, or letrec-syntax forms occur in a top-level body prior to the first expression, they are spliced into the body; see section 11.4.7. Some or all of the body, including portions wrapped in begin, let-syntax, or letrec-syntax forms, may be specified by a syntactic abstraction (see section 9.2).

From the [R6RS Spec, Chapter 7](http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-10.html#node_chap_7)

In this case the:

```scheme
  (record-writer (type-descriptor test-a)
                 (lambda (r p wr) #f))
```

Call is an expression so it cannot proceed a definition.  There are a couple of ways to work around this.  Since you are using Chez Scheme's library you can use Chez Scheme's `module` form to wrap the expression:

```scheme
  (module ()
     (record-writer (type-descriptor test-a)
                    (lambda (r p wr) #f)))
```

A `module` is always a definition, even when it contains expressions.  You can also wrap a `define` around at (effectively defining it for effect).

```scheme
  (define ignore
     (record-writer (type-descriptor test-a)
                    (lambda (r p wr) #f)))
```

You are also correct that the error message when you put the `define-record-type` exposes the fact that `define-record-type` is defined as a macro that expands into a set of definitions using the underlying procedural interface for the record system.  Since `define-record-type` is just a normal macro like any macro a user might define, the expander has to expand it to determine whether it is a definition or an expression.  You can also use `expand` at the repl to see this though, so I'm not sure how much it is really exposing.  Although it is worth noting that the `define` you see in the error message would have either been expanded into a top-level `set!` or part of a `letrec*` depending on context---`define`s are only treated as top-level set! at the top-level, within a body, such as inside a program, library, or the body of a lambda, it becomes a `letrec*`.

**Comment by nulldatamap** [comment]
Okay, thanks for clarifying then.
