### ISSUE TITLE
Improving debug facility

### ISSUE THREAD

**Issue by amirouche** [cisco/ChezScheme#304]
Here is what I have:

```scheme
amirouche@neitram:~/src/scheme/chez/tmp$ cat foo.scm
(import (rnrs))

(define (foo example)
  (let ((bar 1))
    (bar)))

(foo 42)
amirouche@neitram:~/src/scheme/chez/tmp$ scheme --debug-on-exception --program foo.scm
Exception: attempt to apply non-procedure 1
debug> i
#<continuation>                                                   : sl
  continuation:          #<system continuation in ksrc>
  procedure code:        (lambda () (letrec* ((...) (...)) ((...))))
  call code:             (bar)
#<continuation>                                                   : 
```

Is it  possible to know in which module `bar` is defined?

Also, 

- is it possible to have traceback on errors instead of having to enter the debugger?
- the debugger is very crude, it doesn't support sexp editor nor readline (history, autocomplete)

**Comment by amirouche** [comment]
Also, this article is helpful https://www.cs.indiana.edu/chezscheme/debug/

**Comment by jltaylor-us** [comment]
If you want an error handler to print a stack trace then install an error handler that prints stack traces.  #128 

If you want the inspector to support the expression editor (which seems like a pretty good idea to me) then you might have better luck opening an issue specifically for that.  (I'm a little surprised that there isn't one already.)

As for knowing where `bar` is defined... well, first, your question as written doesn't make sense, since there are no modules at all in your example.  Presuming you meant that you wanted to know where the variable was introduced into scope (which still won't necessarily tell you where it was assigned the bad value), that's a good question.  Perhaps one of the maintainers will chime in and tell us if that information is retained in the compiled code (when inspector information is enabled).  Frankly, I'm a little surprised that it kept enough information to know that there was a `bar` in the first place, since `expand/optimize` gets rid of it completely.

**Comment by akeep** [comment]
As @jltaylor-us mentioned, there is no module or library here, so I'm not sure what you mean by that.  However, the `file` command can be pretty useful in the debugger to figure out where the error occurred.  From your example:

```
% scheme --debug-on-exception --program /tmp/foo.scm
Exception: attempt to apply non-procedure 1
debug> i
#<continuation>                                                   : sl
  continuation:          #<system continuation in ksrc>
  procedure code:        (lambda () (letrec* ((...) (...)) ((...))))
  call code:             (bar)
#<continuation>                                                   : file
line 5, character 5 of /tmp/foo.scm
#<continuation>                                                   : 
```

`file` tells you that this exception was thrown at line 5, column 5 of the file (which I put in `/tmp`).

**Comment by amirouche** [comment]
I think this issue can be closed. I am confortable enought with the current state.

Thanks!
