### ISSUE TITLE
X11 path issue on Mac OS X 10.13

### ISSUE THREAD

**Issue by tison1** [cisco/ChezScheme#325]
https://github.com/cisco/ChezScheme/blob/6c738bdfde601b815c296f489697e61c314e4621/c/Mf-a6osx#L20

Actually it is in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tk.framework/Headers/`, there is not a symbol link from `/opt/include/X11`. See https://support.apple.com/en-us/ht201341

**Comment by W4anD0eR96** [comment]
This causes 
```
(cd a6osx && /Applications/Xcode.app/Contents/Developer/usr/bin/make build)
(cd c ; /Applications/Xcode.app/Contents/Developer/usr/bin/make)
gcc  -m64 -Wpointer-arith -Wall -Wextra -Wno-implicit-fallthrough -Werror -O2 -I/opt/X11/include/  -c -DX86_64 -I../boot/a6osx -I../zlib expeditor.c
expeditor.c:888:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [expeditor.o] Error 1
make[1]: *** [build] Error 2
make: *** [build] Error 2
```

I can locally change `-I/opt/X11/include/` t `-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tk.framework/Headers/` and `make` done. But wondering whether there is a more compatible approach.

**Comment by W4anD0eR96** [comment]
@burgerrg any idea?

**Comment by W4anD0eR96** [comment]
ummm, assume users are able to fix it by themselves is well

**Comment by W4anD0eR96** [comment]
One can install [XQuartz](https://www.xquartz.org/) to fix this,  and I think it might worth a troubleshooting document/README/INSTALL

**Comment by burgerrg** [comment]
I don't have XQuartz installed, so I cannot compile Chez Scheme for macOS without modifying c/version.h to remove the LIBX11 definition for macOS. I would welcome a pull request that adds a check for X11/Xlib.h and allows systems without it to compile.

**Comment by W4anD0eR96** [comment]
Relevant #84

**Comment by Hyzeta** [comment]
@W4anD0eR96 #328 has bug while build with X11, and it should not be merged. I will try to fix it.

**Comment by akeep** [comment]
@burgerrg and I had discussed this a little offline and I was planning to take a look at a fix this weekend.

For a little context, X11 is used by the expression editor to interact with the X11 clipboard and, currently, on macOS the LIBX11 flag is also used to decide if the expression editor should interact with the macOS pasteboard.  In many cases (on macOS at least) the paste support isn't really needed because if you are just using the expression editor within the macOS terminal, the terminal itself will trap the paste key combination and paste for you, however, if you are in either an Xquartz terminal or if you are running inside another terminal emulator that does not do this for you, it would be nice to support the macOS pasteboard, even when X11 is not available.

Additionally, I'd prefer that the decision to build in support for X11 be something the configure script decide, similar to the way autoconfig decides these things.  I have some ideas on how this should work, but I'll need to test it out.

So, I'd like to make two changes as part of this:

1. Have X11 support be detected by configure
2. Unentangle the X11 clipboard and macOS pasteboard in the expression editor.

#84 also mentions ncurses.  Unlike X11 which is primarily used for clipboard support, ncurses is needed to support the expression editor.  It is possible to turn off the expression editor (though I've not tested this aspect yet, it should turn off cleanly) if we can detect it is not available in configure, however, it is worth noting that interacting with REPL is a lot less pleasant when the expression editor, which gives you multi-line editing, history search, auto indent, tab completion, and configurable keyboard macros---see sections [Section 2.2. Expression Editor ](http://cisco.github.io/ChezScheme/csug9.5/use.html#./use:h2) and [http://cisco.github.io/ChezScheme/csug9.5/expeditor.html#g130](http://cisco.github.io/ChezScheme/csug9.5/expeditor.html#g130) for details.

I'm not opposed to having configure determine that it could not support the expression editor, though I'd probably want configure to raise a warning, or perhaps require a flag to indicate it was okay to leave it off.

**Comment by Hyzeta** [comment]
New PR #329 , add an option `--without-x` to configure, which allow you to build ChezScheme without X11

**Comment by Hyzeta** [comment]
https://github.com/cisco/ChezScheme/pull/329

**Comment by Hyzeta** [comment]
#329

**Comment by burgerrg** [comment]
@akeep, thanks!

**Comment by hemulens** [comment]
> This causes
> 
> ```
> (cd a6osx && /Applications/Xcode.app/Contents/Developer/usr/bin/make build)
> (cd c ; /Applications/Xcode.app/Contents/Developer/usr/bin/make)
> gcc  -m64 -Wpointer-arith -Wall -Wextra -Wno-implicit-fallthrough -Werror -O2 -I/opt/X11/include/  -c -DX86_64 -I../boot/a6osx -I../zlib expeditor.c
> expeditor.c:888:10: fatal error: 'X11/Xlib.h' file not found
> #include <X11/Xlib.h>
>          ^~~~~~~~~~~~
> 1 error generated.
> make[2]: *** [expeditor.o] Error 1
> make[1]: *** [build] Error 2
> make: *** [build] Error 2
> ```
> 
> I can locally change `-I/opt/X11/include/` to `-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tk.framework/Headers/` and `make` done. But wondering whether there is a more compatible approach.

Hello @TisonKun.
Could you please write exact commands which you use to change `-I/opt/X11/include/` ? 
I am new to C++ and do know know how to do it.

**Comment by TisonKun** [comment]
@hemulens  I think it is a line of makefile template. If you check out current master, you shouldn't take care of it.

**Comment by hemulens** [comment]
@TisonKun Thank you for the tip!
