### ISSUE TITLE
Support cross-compilation from another Scheme implementation

### ISSUE THREAD

**Issue by drbo** [cisco/ChezScheme#33]
It would be nice to be able to cross-compile Chez Scheme using another R6RS Scheme as a host.  Steel Bank Common Lisp supports this, for example.  This would eliminate the need for the binary `.boot` files.

Feel free to close as "won't fix" if this is impractical, but I think that it would be a nice feature.

**Comment by dybvig** [comment]
I'm going to take you up on your offer to close as "won't fix".  It's indeed not practical, since the compiler uses many non-R6RS features to good effect, and it would be a poor bargain to avoid such features and build in a depenency on another Scheme implementation just to avoid distributing boot files,
