### ISSUE TITLE
bug at procedure remove!

### ISSUE THREAD

**Issue by guenchi** [cisco/ChezScheme#332]
```
Chez Scheme Version 9.5
Copyright 1984-2017 Cisco Systems, Inc.

> (define x '(1 2 3 4 5))
> x
(1 2 3 4 5)
> (remove! 1 x)
(2 3 4 5)
> x
(1 2 3 4 5)
> (remove! 2 x)
(1 3 4 5)
> x
(1 3 4 5)
> 
```

**Comment by gwatt** [comment]
The linear update - or "!" suffixed - procedures are not required to update their arguments; they are merely allowed to.

**Comment by olopierpa** [comment]
On Mon, Jul 16, 2018 at 2:31 AM, guenchi <notifications@github.com> wrote:

> Chez Scheme Version 9.5
> Copyright 1984-2017 Cisco Systems, Inc.
>
> > (define x '(1 2 3 4 5))
> > x
> (1 2 3 4 5)
> > (remove! 1 x)
> (2 3 4 5)
> > x
> (1 2 3 4 5)
> > (remove! 2 x)
> (1 3 4 5)
> > x
> (1 3 4 5)
> >
>
>
No bug here. Working as specified.

The list you pass to remove! MAY be DESTROYED by the remove! procedure, and
after the application of remove! the conses which were in the original list
are in an undefined state.

In your examples you must: (set! x (remove! whatever x))

Secondarily, you should not modify a literal constant list, as you are
doing here, even if this is not causing problems apparent from this short
interaction.

**Comment by olopierpa** [comment]
Il giorno 16 luglio 2018, alle ore 08:22, 陈梓立 <notifications@github.com> ha scritto:

>
>
>The linear update - or "!" suffixed - procedures are not required to update their arguments; they are merely allowed to.
>So why we need a remove!? Let's say all is remove and do (set! x (remove whatever x)), it is always clearly what I want to do. The problem is we have a remove! and say, hey, I'm not sure what it would produce.

It produces something which is partially specified.

It is useful because implementations are allowed to (and typically do) take advantage of the less specified result in order to use a faster algorithm.

So, in cases where both delete! and remove could be used, typically 
the delete! version will be faster. Typically, MUCH faster.

**Comment by tison1** [comment]
@olopierpa ok, could we do something let `remove!` keep consistency, if we could not, what is the reason?

**Comment by olopierpa** [comment]
On Mon, Jul 16, 2018 at 4:40 PM, 陈梓立 <notifications@github.com> wrote:

> @olopierpa <https://github.com/olopierpa> ok, could we do something let
> remove! keep consistency, if we could not, what is the reason?
>

Define "consistency".

In the first post you copied what Chez returns for your expressions (which
is correct). You didn't tell us what you are expecting to see instead.

**Comment by tison1** [comment]
```scheme
Chez Scheme Version 9.5.1
Copyright 1984-2017 Cisco Systems, Inc.

> (define x '(0 1 2 3))
> (remove! 1 x)
(0 2 3)
> x
(0 2 3)
> (define x '(0 1 2 3))
> (remove! 0 x)
(1 2 3)
> x
(0 1 2 3)
> 
```

`remove!`'s return values are consistent, but what it does on `x` are not. The first execution it modifies `x` and the second it doesn't.

**Comment by akeep** [comment]
Let's understand a bit what is going on here.

`remove!` is a function, and in a pass by value language, the body of the `remove!` function is not passed `x` it passed the _value_ of `x`.  So, even if it wanted to it could modify `x`.

So, what is the _value_ of `x`?  Well, it is the list 0, 1, 2, 3, however, what is a list, in scheme? It is a sequence of cons cells or pairs, where the first element of the pair contains a value (0, 1, etc.) and the second element points to the next pair in the list or `'()` (aka null), at least if it is a proper list.

To visualize this, the list in this case is:

```
   +---+---+  +---+---+  +---+---+  +---+-----+
x: | 0 |  -+->| 1 |  -+->| 2 |  -+->| 3 | '() |
   +---+-+-+  +---+---+  +---+---+  +---+-----+
```

And the value passed is just the pointer to the start of this list.  `remove!` is allowed to modify the pairs of the list.  For instance when we `remove!` 1, the pair containing 0, which points to the pair containing one, is modified to point to the cell containing 2.  Resulting in the following:

```
   +---+---+             +---+---+  +---+-----+
x: | 0 |  -+------------>| 2 |  -+->| 3 | '() |
   +---+-+-+             +---+---+  +---+-----+
                           ^
              +---+---+    |
              | 1 |  -+----+
              +---+---+
```

Note that the pair holding 1 still exists and still points at the pair containing 2, it is just the pair containing 0 that has been modified.  So if you had a variable whose value was the pair containing 1 you would still see the 1 in that list:

```
% scheme
Chez Scheme Version 9.5.1
Copyright 1984-2017 Cisco Systems, Inc.

> (define x (list 1 2 3 4))
> (define x (list 0 1 2 3))
> (define y (cdr x))
> x
(0 1 2 3)
> y
(1 2 3)
> (remove! 1 x)
(0 2 3)
> x
(0 2 3)
> y
(1 2 3)
> 
```

Again, this is because `remove!` is only mutating the pairs in the list, not the _value_ which was passed to it, which was really just a pointer to the first pair.  When we `remove!` 0, there is nothing in the list to modify, since the it is only the first pair that is impacted, and nothing in the list points to that pair.

```
             +---+---+  +---+---+  +---+-----+
r:           | 1 |  -+->| 2 |  -+->| 3 | '() |
              +---+-+-+  +---+---+  +---+-----+
                ^
   +---+---+    |
x: | 0 |  -+----+
   +---+---+
```

Where `r:` here is the pair returned by `remove!` as a result.

So, how is this different from `remove`?  Well, `remove` is not allowed to modify the pairs of the list that was passed to it, so if we started back with our original list:

```
   +---+---+  +---+---+  +---+---+  +---+-----+
x: | 0 |  -+->| 1 |  -+->| 2 |  -+->| 3 | '() |
   +---+-+-+  +---+---+  +---+---+  +---+-----+
```

`remove` 1 would need to rebuild the pairs of the list leading up to this, giving us the following result:

```
   +---+---+  +---+---+  +---+---+  +---+-----+
x: | 0 |  -+->| 1 |  -+->| 2 |  -+->| 3 | '() |
   +---+-+-+  +---+---+  +---+---+  +---+-----+
                           ^
                 +---+---+ |
              r: | 0 |  -+-+
                 +---+---+
```

So, we needed to allocate a new pair containing 0 that points to 2 so that the original list still exists unaltered.  This is what differentiates `remove!`, which never needs to allocate new pairs, but may modify the existing pairs from `remove` which never modifies existing pairs, but may need to allocate new pairs.

Another way to think about this, is that "passing `x`" to `remove!` is really just passing an expression whose value happens to be the list 0, 1, 2, 3?  For instance:

```
> (remove! 1 (iota 4))
(0 2 3)
```

What would `remove!` "modify" in its argument?

**Comment by tison1** [comment]
@akeep thanks! I think this is the "answer" of the issue.
Sorry for I am so noob.

@guenchi do you accept the explain above?

**Comment by guenchi** [comment]
@akeep 

thx for explanation.
