### ISSUE TITLE
Mutexes and condition variables with names

### ISSUE THREAD

**Issue by jessymilare** [cisco/ChezScheme#372]
In many other scheme implementations, CL implementations and also SRFI 18 and SRFI 21, mutexes and condition variables have an optional field called 'name', both for developing and debugging.

This could be accomplished by creating a new field "name" in mutex and condition records and then redefining make-mutex and make-condition to accept an optional argument 'name'. This would change the number of arguments for $make-mutex and $make-condition, which AFAIK are only directly called in s/prims.ss, so that would not be a big issue.

If this is desired, I can make these changes (and also tests and LOG entry) and create a pull request.

**Comment by yjqww6** [comment]
How about just using a weak eq hashtable to attach a name to all sorts of objects?

**Comment by jessymilare** [comment]
It would (1) not be printed and (2) occupy more space. During debugging, if you ask to show local variables or the arguments of a procedure and see a mutex or condition, it's name wouldn't be printed, you would need to inspect it, etc. I just think displaying the mutex/condition name is a nice feature Chez Scheme could have.

**Comment by jessymilare** [comment]
Alright, I'm not gonna implement an ideia the maintainers didn't like.

**Comment by dybvig** [comment]
Thanks for the feature suggestion and offer to implement it.  Please don't assume the maintainers don't like the idea simply because we're silent---as you can see from the number of oustanding pull requests and issues, we're not keeping up at present.

In this case, while I don't recall encountering a situation where a mutex or condition-variable name would have been useful, I don't object to supporting the feature if others would find it useful.  So if you think it's useful enough to spend time on a pull request, I'll look it over and, possibly after requesting changes, pull it.  I would suggest that the name, if supplied, be a symbol to simplify printing and for consistency with procedure and record-type names.

In general, when deciding whether to add a debugging aid, the decision hinges on whether and how it can be done without significant run-time cost.  In this case, the simple solution of adding an extra name field to each mutex and condition variable would make the objects larger and increase the cost of allocating and collecting them.  On the other hand, a typical program probably doesn't allocate many mutexes and condition variables or allocates them as part of other structures, so the overhead of the extra field would likely be small if not insignificant for most programs.

Alternatively, you could subclass the mutex and condition record types so that mutexes and condition variables without name fields wouldn't be any larger.  This would make the mutex? and thread-condition?  predicates slightly more expensive, but perhaps not significantly.

**Comment by jessymilare** [comment]
All right, thank you for the response.

I think that it would be better if the name is a string, but a symbol would be ok too.

As for the kind of solution, I think subclassing the record types would be better. If you have some code that you want to be fast, you would probably call (optimize-level 3), which would skip type checking and the predicates would only be called if requested explicitly by the programmer. In any case, the predicates should be as fast as before when called with unnamed mutexes and conditions, right?

**Comment by jessymilare** [comment]
On a second thought, it's better to keep the mutex and condition types sealed. (De)allocation is done only once for each obj, while type checking is probably done more than once for each obj.
