### ISSUE TITLE
Create a bytevector object from a C array

### ISSUE THREAD

**Issue by amirouche** [cisco/ChezScheme#414]
Is is possible to have procedure to expose a memory region (C array) as bytevector without making the memory region part of GC panopticon?

**Comment by amirouche** [comment]
The problem I have is that I need to unpack (parse) a C array that is owned by a library. The C struct definition looks like the following:

```c
struct item {
	const void *data;
        size_t size;
}
```

What I am doing right now, is copying the memory region into a bytevector if size `item->size` using the following code:

```scheme
    (define (item->bytevector item) ;; XXX: copy!
      (let* ((item (make-ftype-pointer %item item))
             (data (ftype-ref %item (data) item))
             (size (ftype-ref %item (size) item))
             (bytevector (make-bytevector size)))
        (let loop ((index (- size 1)))
          (when (>= index 0)
            (let ((value (foreign-ref 'unsigned-8 data index)))
              (bytevector-u8-set! bytevector index value)
              (loop (- index 1)))))
        bytevector))
```

I would like to avoid the copy.

**Comment by amirouche** [comment]
After the copy, the bytevector is parsed into scheme objects.

To by honest, in my usecase it more performant than equivalent Java code, but it would be nice to have if it is easy to do.

**Comment by akeep** [comment]
It is not possible to have a scheme bytevector outside of the scheme heap.  There are two reasons for this.  First, a bytevector is not just a blob of data in memory, it has a header word that identifies it as a bytevector, specifies the length of the bytevector, and indicates if it is mutable.  This word would need to immediately precede the data in memory.  Second, when the garbage collector encounters a scheme object during collection, it will attempt to copy it.  There is a check in the collector to make sure the pointer to the object is within the scheme heap (which it would not be in this case) and when it is not in the heap the garbage collector raises an exception, since it assumes something has gone horribly wrong.

It is worth noting that foreign pointers are stored as exact integers (either fixnums or bignums, depending on the value of the pointer), so these are not confused with scheme objects.  It is also possible to store raw pointers in records using Chez Scheme's legacy record system described in [Section 7.15. Legacy Record Types](http://cisco.github.io/ChezScheme/csug9.5/objects.html#./objects:h15).

**Comment by amirouche** [comment]
Thanks.
