### ISSUE TITLE
unable to compile in centos 7 with gcc 5.3.1

### ISSUE THREAD

**Issue by zhuojun** [cisco/ChezScheme#43]
Hello
After execute commands listed below
git clone --recursive https://github.com/cisco/ChezScheme.git
cd ChezScheme
./configure
make install

I got following messages:
`Mf-base:447: recipe for target 'bootall' failed
Mf-base:146: recipe for target 'allx' failed
Mf-base:157: recipe for target 'bootstrap' failed
Makefile:20: recipe for target 'build' failed
Makefile:22: recipe for target 'install' failed
`
my gcc version is 5.3.1, it is a virtual machine with centos 7 installed.

I don't know what's wrong here, is it dependencies missing or some other issue?

please find attached full version of make install output
[error_log.txt](https://github.com/cisco/ChezScheme/files/261079/error_log.txt)

**Comment by akeep** [comment]
Hi @zhuojun,

How much memory do you have configured on your virtual machine?

I've done some compiles on Ubuntu and Fedora virtual machines and for the 64-bit version of Chez Scheme you are compiling, I usually configure my virtual machines to provide 4GB of system memory.  I've found with 2GB or less, compiling the 64-bit version fails for me.  That said, I would have expected to see a "Killed" message in your error log, which is usually what the operating system prints when it kills a program because the system ran out of memory.

When I get some spare time I can try to spin a virtual machine and test this myself.

**Comment by zhuojun** [comment]
Previously I set the memory to 1G, after I set it to 4G, the compilation was success. I do noticed the kill message from OS but didn't understand why it appears at first place. Thanks akeep!

**Comment by dybvig** [comment]
The Linux kernel can overcommit available memory.  When a process touches a page it has been given and there's nowhere to allocate it physically, the O/S picks a (possibly different) process to kill.  The Scheme process must have looked like a good choice.  It probably was a good choice, since it was likely going to need more than was available.to compile cpnanopass.ss.
