### ISSUE TITLE
Consider creating a mailing list for Chez

### ISSUE THREAD

**Issue by michaellenaghan** [cisco/ChezScheme#44]
At the moment this issues list is the only way people can talk about Chez. (There's an IRC channel, but that's only for real-time communication.)

**Comment by olopierpa** [comment]
I agree that a mailing list is desirable, and since nobody acted on this, I
created one on google group here:
https://groups.google.com/forum/#!forum/chez-scheme

I hope I have not stepped on anyone's toes. If/when a more official m.l. is
created I'll close this one.

**Comment by jikzpmtt** [comment]
An alternative to consider is Discourse. It's more of a forum than a mailing list but I think it would suit this project well. We don't yet strictly meet their requirements for the free open-source project hosting, but I suspect they'd let us have one anyway.

http://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/

**Comment by akeep** [comment]
I'd like to establish an official mailing list for Chez Scheme.  Right now, I think I'd like to do that as a Google groups mailing list.

@olopierpa I would appreciate it if you closed the forum you started.  I'm going to draft a welcome message to be the first post on the forum so that we have a good starting point for discussions.

I had intended to create the mailing list no later than last weekend, and was a bit surprised to find there was already one there!

Thanks,
-andy:)

**Comment by olopierpa** [comment]
ok

**Comment by akeep** [comment]
I've recreated the chez-scheme mailing list as a Google group: chez-scheme.

You can find the group at: https://groups.google.com/forum/#!forum/chez-scheme

I've also created a new (minimal) home page for Chez Scheme with the official Chez Scheme Users Guide and v9.4 release notes at: http://cisco.github.io/ChezScheme

Thanks to @olopierpa for closing the chez-scheme group so that I could create an official one.

**Comment by michaellenaghan** [comment]
Andy, if you click the Edit button next to the repository name:

![screen shot 2016-05-15 at 2 14 47 pm](https://cloud.githubusercontent.com/assets/176481/15275956/a1f1f018-1aa7-11e6-9ecb-f341e09db5af.png)

there's a spot you can put http://cisco.github.io/ChezScheme/ so that it will show up at the top of the page:

![screen shot 2016-05-15 at 2 15 21 pm](https://cloud.githubusercontent.com/assets/176481/15275961/d3ed6ba6-1aa7-11e6-858b-87e57e08ac6c.png)

I'd also suggest creating a link in README.md so that people can find the URL in forks, etc.

**Comment by akeep** [comment]
Hey Michael, unfortunately I don't have access to make those kinds of changes.  I'll have to put in a request with my colleague that manages Cisco's public github repository.

**Comment by michaellenaghan** [comment]
Well, if we add a link to README.md it will *almost* serve the same purpose: people will see it as soon as they land on https://github.com/cisco/ChezScheme. It will also have the added benefit of being in any clones and forks.

Come to think of it, maybe the contents of http://cisco.github.io/ChezScheme/ should be in README.md...?

For consideration. There's a lot of useful info in what you created. I'd just like to make it as easy as possible to find.
