### ISSUE TITLE
it does not supported utf-8

### ISSUE THREAD

**Issue by kerwinxu** [cisco/ChezScheme#466]
win10,chinese ,vscode 
i write the fellowing code with vscode :
(display "HelloWorld ,徐恒晓")
(exit)
then scheme this file 
Chez Scheme Version 9.5.3
Copyright 1984-2019 Cisco Systems, Inc.

HelloWorld ,寰愭亽鏅
then i save utf16le and utf16be encoding , output the following 
Chez Scheme Version 9.5.3
Copyright 1984-2019 Cisco Systems, Inc.

Exception: variable 锟斤拷\x0; is not bound

**Comment by burgerrg** [comment]
Chez Scheme uses the UTF-8 encoding by default for files. If you want to use a different encoding, you must set the `current-transcoder` parameter and then call `load`:

```
Chez Scheme Version 9.5.2
Copyright 1984-2019 Cisco Systems, Inc.

> (parameterize ([current-transcoder (make-transcoder (utf-16-codec))])
    (load "hello.ss"))

HelloWorld ,徐恒晓
>
```

hello.ss is stored in UTF16LE encoding:
```
(display "HelloWorld ,徐恒晓")
(newline)
```

**Comment by burgerrg** [comment]
If you want `scheme` to load the file, it must be stored in UTF-8.

**Comment by kerwinxu** [comment]
maybe i use win10 and vc 2019, then error .
i build chezscheme :
c/build.vat ta6nt
i write the below code into a file  with "utf-8"
(display "HelloWorld ,徐恒晓")
it does not work well .

make workareas (in msys2) , it build ta6nt and a6nt , the same broblem .

**Comment by burgerrg** [comment]
Do you see this?
![Screen Shot 2019-10-14 at 11 01 39 AM](https://user-images.githubusercontent.com/6304842/66761447-0a6b5700-ee72-11e9-87a8-5c785fcf059a.png)

If so, it's because the Windows console does not support UTF-8. You need to use a Unicode terminal such as "Git Bash". Then you should see this:
![Screen Shot 2019-10-14 at 11 03 28 AM](https://user-images.githubusercontent.com/6304842/66761591-4bfc0200-ee72-11e9-9fe8-a9dca142c9a1.png)
