### ISSUE TITLE
suggestion for hashtable interface

### ISSUE THREAD

**Issue by ocyzl** [cisco/ChezScheme#483]
It would be nice if there were a single function that tells you whether a given key is present in a hashtable, and also tells you the associated value if it is.  Like this, but faster because it need only hash the key once:
<pre>
(define (hashtable-get ht key)
  (if (hashtable-contains? ht key)
      (values #t (hashtable-ref ht key 'whatever))
      (values #f 'whatever)))
</pre>

**Comment by jltaylor-us** [comment]
I can't imagine how I'd ever it more convenient to handle multiple return values rather than a single value in a lifted domain, but you can easily write this yourself.
```scheme
(define hashtable-get
  (let ([$not-found (gensym "not-found")])
    (lambda (ht key)
      (let ([v (hashtable-ref ht key $not-found)])
        (values (eq? $not-found v) v)))))
```
Of course, if you know what values might appear in the hashtable then you could easily use some other value for `$not-found` and avoid having to allocate a special value for it.

**Comment by ocyzl** [comment]
Thanks.  That's very helpful.

**Comment by jltaylor-us** [comment]
@akeep pointed out that technically the function shouldn't let `$not-found` get returned, because then someone could go put the value that the function created specifically to never appear in any hashtable into the hashtable.
