### ISSUE TITLE
Unexpected behavior with syntax-case inside module form

### ISSUE THREAD

**Issue by amirouche** [cisco/ChezScheme#524]
Given the following program where there is module called `library.0` that export a `syntax-case` macro relying on a procedure:

```scheme
(import (prefix (only (chezscheme) begin module import export implicit-exports) $))

($begin
  ($module library.0 () ($implicit-exports #t) ($import (chezscheme))
    (define-syntax vanish-define
      (lambda (stx)
        (syntax-case stx ()
          [(_ def (vanish ...))
           (for-all identifier? #'(def vanish ...))
           #'(make-vanish-define #'def #'vanish ...)])))
    (define (make-vanish-define def . to-vanish)
      (lambda (stx)
        (define (vanish? id)
          (memp (lambda (x) (free-identifier=? id x)) to-vanish))
        (syntax-case stx ()
          [(_ name . _)
           (and (identifier? #'name) (vanish? #'name))
           #'(begin)]
          [(_ (name . _) . _)
           (and (identifier? #'name) (vanish? #'name))
           #'(begin)]
          [(_ . r) (cons def #'r)])))
    ($export vanish-define))
  ($import (chezscheme) library.0)
  (let-syntax ([define (vanish-define define (cons*))]) #t))
```

The output of Chez is:

```sh
% scheme --script test.scm
Exception: variable make-vanish-define is not bound

% scheme --program test.scm
Exception: attempt to reference out-of-phase identifier make-vanish-define at line 10, char 15 of test.scm
```

What am I doing wrong ?

**Comment by lemvik** [comment]
Have you tried to mark `make-vanish-define` as [`meta` definition](https://cisco.github.io/ChezScheme/csug9.5/syntax.html#./syntax:s36)?

I think the reason (but that's just a guess) here is that `vanish-define` gets expanded by expander into `make-vanish-define` which should be expanded then, but it's not present either in the scope of the original form being expanded (since it's not exported from module) nor in compiler/expander scope (since it's not marked as `meta`).

No idea why different errors with `--script` and `--program`.

**Comment by amirouche** [comment]
Woot :tada: ! It solves that problem thanks a lot @lemvik !
