### ISSUE TITLE
rename main branch to main 

### ISSUE THREAD

**Issue by fluffy** [cisco/ChezScheme#549]

**Comment by owaddell** [comment]
GitHub now appears to [support](https://github.com/github/renaming#rename-existing) this kind of renaming in a way that re-targets pull requests and such. How do we go about this?

**Comment by jltaylor-us** [comment]
It's kind of amazing that it's impossible to find the answer to such a simple question.

From what I've been able to gather, the answer is "nothing".  Forks are this strange façade that pretends to be a separate repo to the outside world, and as such they have their own set of branches, tags, etc. that won't change at all.  A fork's default branch name is unrelated to its parent's default branch name.

What it does impact is any git repo (e.g. local repos on developer machines) that has the main ChezScheme repo as a remote.  The instructions for updating a "local clone" are pretty straightforward, and are presented to the user when they visit the GitHub page for a project that's renamed its default branch:
<img width="496" alt="Screen Shot 2021-04-02 at 6 33 04 PM" src="https://user-images.githubusercontent.com/18684406/113461476-be57fd80-93ea-11eb-96e7-4397509eb68d.png">
Anyone who's managed to add a remote that has a name other than "origin" ought to know what they need to do when they see these directions, as well.

Of course, those directions didn't actually work for me because apparently cloning with `--depth=1` also sets up the remote to fetch a specific ref rather than all refs, and `git fetch` will fail if that ref doesn't exist.  A simple edit to `.git/config` is the quickest way to fix that (after you've spent a half hour googling why your repo is broken to figure out which one line you need to edit, trying to use the CLI to update the remote instead and accidentally losing the "shallowness" of your repo, figuring out how to get that back, and deciding you should have just edited the file directly in the first place).

**Comment by fluffy** [comment]
It looks like the github rename owaddell mentioned works well. I will do that and hope nothing bad happens (we can undo it if bad stuff happen )
