### ISSUE TITLE
FFI - Unable to use double pointer to ftype struct in foreign-procedure call

### ISSUE THREAD

**Issue by mspaulding06** [cisco/ChezScheme#557]
After spending a lot of time trying different things I have decided that this may be a bug.  Here is the relevant code example.

```
(define lib (load-shared-object "libssh2.so.1.0.1"))

(define-ftype ssh-agent* uptr)

(define-ftype ssh-agent-publickey
              (struct
                [magic unsigned-int]
                [node void*]
                [blob (* unsigned-8)]
                [blob_len size_t]
                [comment (* char)]))

(define c-ssh-agent-get-identity
  (foreign-procedure "libssh2_agent_get_identity"
                     (ssh-agent* (* (* ssh-agent-publickey)) (* ssh-agent-publickey)) int))
```

When loading this code in the REPL and get the following error:

```
Exception: invalid foreign-procedure argument type specifier (* (* ssh-agent-publickey)) at line 15, char 34 of test.scm
```

If I modify the call to `foreign-procedure` slightly to remove the double pointer like this:

```
(define c-ssh-agent-get-identity
  (foreign-procedure "libssh2_agent_get_identity"
                     (ssh-agent* (* ssh-agent-publickey) (* ssh-agent-publickey)) int))
```

Then everything loads just fine.

I've also tried using `define-ftype` to see if that changes anything with the following definitions:

```
(define-ftype ssh-agent-publickey* (* ssh-agent-publickey))
(define-ftype ssh-agent-publickey** (* ssh-agent-publickey*))

(define c-ssh-agent-get-identity
  (foreign-procedure "libssh2_agent_get_identity"
                     (ssh-agent* ssh-agent-publickey** ssh-agent-publickey*) int))
```

This still fails, but the error message changes slightly to this:

```
Exception: invalid (non-base) foreign-procedure argument ftype ssh-agent-publickey* at line 18, char 55 of test.scm
```

**Comment by akeep** [comment]
It may seem a little odd, but this is actually the intended behavior.

The idea is basically this.  When you say:

```scheme
(define x (make-ftype-pointer ssh-agent-publickey (foreign-alloc (ftype-sizeof ssh-agent-publickey))))
```
`x` contains a value of type `(* ssh-agent-publickey)`---it i a pointer to an `ssh-agent-publickey`.  So the `foreign-procedure` expects that you will refer to this argument type as `(* ssh-agent-publickey)`... however while `(* (* ssh-agent-publickey))` defines a valid type, it is not one you can use, because `make-ftype-pointer` doesn't understand `(* ssh-agent-publickey)`:

```scheme
(define x (make-ftype-pointer (* ssh-agent-publickey) 0))
Exception: invalid syntax (make-ftype-pointer (* ssh-agent-publickey) 0)
```

So, as you suspected, you need to define the type `ssh-agent-publickey*`:

```scheme
(define-ftype ssh-agent-publickey* (* ssh-agent-publickey))
(define c-ssh-agent-get-identity
  (foreign-procedure "libssh2_agent_get_identity" (void* (* ssh-agent-publickey*) (* ssh-agent-publickey)) int))
(define store (make-ftype-pointer ssh-agent-publickey* (foreign-alloc (ftype-sizeof ssh-agent-publckey*))))
(define prev (make-ftype-pointer ssh-agent-publickey 0)) ;; null pointer to indicate no previous:
(c-ssh-agent-get-identity ??? store key)
```

I don't know how to construct the `LIBSSH2_AGENT*` value that is the first argument to `libssh2_agent_get_identity` and my macOS man pages seem to indicate there should be a `libssh2_session_init` to give me a `LIBSSH2_SESSION *`, but this `libssh2_session_init` does not seem to be a function symbol in my `libssh2.dylib`, so I've not been able to test this past make sure that these things compile.

Hope this helps.

**Comment by jltaylor-us** [comment]
I was just about to comment something similar (if less detailed) to @akeep's example after searching and finding the last comment to #270.

I didn't find anything in the docs about this strange little gyration being required, so IMO it's either a bug that the original code didn't work or a bug in the documentation.  (Most likely a bug in the documentation:  Where it says (* _ftype_) is one of the valid forms for a parameter in `foreign-procedure` it should instead say (* _ftype-name_) [and presumably the same for (& _ftype_)].)

**Comment by akeep** [comment]
Yes, this should be documented better.

The reason this works this way is that the `ftype-pointer` system builds on top of the Chez Scheme record system, with each `ftype-pointer` object being a combination of an ftype type descriptor (`ftd`) which is derived from the record system's `rtd` and the `ftd` identifies the type of the object... this means that ftypes are effectively nominally typed, so two ftypes with the same layout are not interchangeable.  This is why an ftype of `(* (* ssh-agent-publickey))` doesn't work as an argument, because `(* ssh-agent-publickey)` is effectively anonymous, making it impossible to construct a useful ftype value.

Part of the reason for this design was to leverage the existing record system and part of it was to avoid the expense of computing structural type equivalence at run time.  The inheritance supported by ftypes (where an ftype can be treated as the first element in the type) also complicates structural type equivalence a bit.

**Comment by mspaulding06** [comment]
Does this mean that it is not possible to create a `foreign-procedure` for a C function that takes a double pointer?

The only solution I can think of is to create a wrapper function in C that does not require a double pointer and then create a `foreign-procedure` for that.  Would that be the most optimal solution in this case?

Example being something like:

```
struct libssh2_agent_publickey *ffi_get_identity(LIBSSH2_AGENT *agent, struct libssh2_agent_publickey *prev)
{
  int retval = 0;
  struct libssh2_agent_publickey *store = malloc(sizeof(struct libssh2_agent_publickey*));

  retval = libssh2_agent_get_identity(agent, &store, prev);

  if (retval == 0) {
    return store;
  }

  return NULL;
}
```

**Comment by akeep** [comment]
No, you can call a function with a pointer to double.  You don't actually need the ftype system to do this, after all a pointer is just a pointer, neither C nor Scheme really care about the type as long as there is enough space to store the result.  Without the ftype system, this looks something like:

```scheme
> (load-shared-object "libc.dylib")
> (define read-double (foreign-procedure "scanf" (string void*) int))
> (define d (foreign-alloc (foreign-sizeof 'double)))
> (read-double "%lf" d)
4.75
1
> (foreign-ref 'double d 0)
4.75
```

The ftype system is largely just to make it easier to deal with structured data.  With that in mind though, we created ftype equivalents for all the built in types, so you can also do:

```scheme
> (define read-double-2 (foreign-procedure "scanf" (string (* double)) int))
> (define d2 (make-ftype-pointer double (foreign-alloc (ftype-sizeof double))))
> (read-double-2 "%lf" d2)
7.25
1
> (ftype-pointer->sexpr d2)
7.25
> (ftype-ref double () d2)
7.25
```

The only thing the ftype system enables in `foreign-procedure` that wasn't there before is passing and returning `struct` types directly using the `(& ftype-name)` syntax.

The only function types that are not directly supported is variable arity functions--not that we cannot call them for scheme, but you have to add a direct entry for each call... similar to the way I specified a 2-argument `scanf` call above.

**Comment by mspaulding06** [comment]
No, I understand that you can do that.  I don't think I made myself clear.  By "double pointer" I meant a "pointer to a pointer".  In the code example I provided I am calling `libssh2_agent_get_identity` which takes a `struct libssh2_agent_publickey**` as the second argument which it fills with the next public key entry in the store.  I haven't been able to figure out how to do that and instead tried wrapping the function as above so that the interface only includes single pointers, which does work.  It's just not what I was hoping for.

**Comment by akeep** [comment]
The example I originally replied with had an example of how to do a double pointer in it:

From my original response:
```scheme
(define-ftype ssh-agent-publickey* (* ssh-agent-publickey))
(define c-ssh-agent-get-identity
  (foreign-procedure "libssh2_agent_get_identity" (void* (* ssh-agent-publickey*) (* ssh-agent-publickey)) int))
(define store (make-ftype-pointer ssh-agent-publickey* (foreign-alloc (ftype-sizeof ssh-agent-publckey*))))
(define prev (make-ftype-pointer ssh-agent-publickey 0)) ;; null pointer to indicate no previous:
(c-ssh-agent-get-identity ??? store key)
```

The `(* ssh-agent-publickey*)` is a pointer to a pointer to an `ssh-agent-publickey`.
