### ISSUE TITLE
Control Flow Analysis?

### ISSUE THREAD

**Issue by amirouche** [cisco/ChezScheme#576]
Does Chez use control flow analysis? What file or files should I look into? Any references I must read?

**Comment by akeep** [comment]
Chez Scheme does not use control flow analysis.

**Comment by akeep** [comment]
I wanted to follow-up on this, because a friend of mine pointed out that I may have interpreted the question a bit narrowly.

When someone says control-flow analysis, I tend to interpret it as Shiver's kCFA, which we do not use in Chez Scheme.

However, Chez Scheme's source optimizer, `cp0` (in `cp0.ss`) performs an online control-flow analysis.  I tend to think of `cp0` as a function inliner with constant propagation, constant folding, copy propagation, etc., but of course, determining which function to inline is fed by the fact that variable bindings are tracked through the control-flow of there program.  You can read more about it in _Fast and Effective Procedure Inlining_ by Oscar Waddell and R. Kent Dybvig.

There are also a couple of data-flow analysis passes.  I usually, perhaps unfairly, distinguish the two in that control-flow analysis is discovering new control flow (by determine functions being called) whereas data-flow analysis is tracing a fixed control flow.  The passes `np-expose-basic-blocks` and `do-live-analysis!` are both reverse-data-flow passes.  The `np-expose-basic-blocks` pass is an intra-procedural analysis to determine the boundaries of the basic blocks within the function and operates over the IR directly.  The`do-live-analysis!` pass,  operates over the control-flow graph generated by `expose-basic-blocks` to build the conflict graph for the graph-coloring register allocator.

Anyway, hope that helps!

**Comment by amirouche** [comment]
Great reply! Thanks :+1:
