### ISSUE TITLE
thread is blocked unexpectly

### ISSUE THREAD

**Issue by yjqww6** [cisco/ChezScheme#58]
I tried to embed chez scheme to a program and  created a thread running a loop. But after a short while, the thread was blocked unexpectly and left the work unfinished.

I try simplified code in repl, and similar things happened.
As follow, after the first time I check a's value, I found it increase similar numbers each time I check it no matter how long I wait. More exactly, it depends on how many times I input things to the repl. The CPU usage is always 0%.

```
> (fork-thread (lambda () (let loop ([i 0]) (set! a i) (loop (+ i 1)))))
#<thread 1>
> a
537411480
> a
537900424
> a
538421584
> a
538945213
> a
539470650
> a
539994892
```
Is there a way to avoid this?

I use a 32-bit threaded version In Windows 7.

**Comment by yjqww6** [comment]
I tested it on 64-bit Linux, the code work as expected and didn't block.

**Comment by dybvig** [comment]
I believe the problem is that the WIN32 definition of `s_ee_read_char` in `expeditor.c` is not deactivating the thread before calling (and possibly blocking on) `ReadConsoleInput`.  When the background thread, which is busily creating and dropping bignums once i gets out of fixnum range, detects it's time to do a collection, the blocked but still active main thread prevents the collection from occurring, effectively blocking the background thread as well.  You can verify this is the problem by setting collect-notify to `#t` and seeing if collections stop after a while.  Or you can go ahead and insert calls to `deactivate_thread` and `reactivate_thread` around the call to `ReadConsoleInput` (following the pattern in the non-WIN32 definition of `s_ee_read_char`) and see if that fixes the problem.

In the 64-bit version, i wouldn't have exceeded the fixnum range in your test (assuming no time travel), so no bignums were allocated, and no collections were needed.

**Comment by yjqww6** [comment]
@dybvig  I have modified the code according to your words and recompiled it, and it seems the problem do not occurs anymore.
