### ISSUE TITLE
Why does it install hardlinks instead of symlinks?

### ISSUE THREAD

**Issue by averms** [cisco/ChezScheme#593]
It is standard in the Unix world to use symlinks when you want to call an executable by a different name. Busybox, Lz4, and ImageMagick all use this pattern. However, Chez installs `scheme-script`, `petite`, and `scheme` as hardlinks to the same inode. This is confusing and AFAIK unnecessary.

Can it be revised to use symlinks instead?

**Comment by jltaylor-us** [comment]
You are aware that Chez Scheme predates all of those packages by decades, right?  I’m not aware of any actual standard that says to prefer symlinks over hard links, and you have not offered any technical reason to do so.

**Comment by averms** [comment]
The technical reason is that symlinks are easily discoverable with `ls --color=auto` and `file`. Discovering _that_ an inode has multiple hard links to it is not that bad, but discovering which filenames are linked to it is certainly a bit more involved. Practically, the reason I opened this issue is that I ran `strip` on `scheme` and was surprised when all 3 of them were stripped.

> You are aware that Chez Scheme predates all of those packages by decades, right?

I am now :). Also, looking at my `/usr/bin`, I see a few more hard links, e.g., `g++` has the same inode as `c++`.

**Comment by jltaylor-us** [comment]
Sounds to me like your problem is not with the files being multiply-linked, but that you didn't _know_ they were multiply linked.  It's trivial to tell; just like at the link count (column 2) in the output from `ls -l`.  Or [build your own](https://unix.stackexchange.com/questions/123138/ls-color-how-to-color-executable-hard-links) version of GNU `ls` that chooses to apply its coloring rules in a different order.

Discovering which filenames point to the same file is just as easy for hard links as symlinks, presuming you want to do it correctly and handle chains of symlinks.  See, for example, [this](https://superuser.com/a/90853) one-liner using the `-samefile` operator of `find`.

For what it's worth, there was a historical reason for using hard links:

> The reason why we used hard links originally is that one could install Petite Chez Scheme only, Chez Scheme only, or both by installing first one then the other, in either order.  One could also uninstall one or the other after having installed both. Hardlinking the name of the second installed executable to the name of the first installed executable was a natural way of insuring that only one copy of the executable was installed and that uninstalling one package didn't disrupt even concurrent use of the other.

**Comment by averms** [comment]
I see. Thank you for the information.
