### ISSUE TITLE
foreign-callable test raises 0xc0000409 STATUS_STACK_BUFFER_OVERRUN on Windows 10

### ISSUE THREAD

**Issue by burgerrg** [cisco/ChezScheme#595]
Chez Scheme 9.5.6 64-bit non-threaded on Windows 10 Pro 21H2 19044.1288

One of the foreign mats calls uses an ftype function pointer to a foreign-callable Scheme procedure. The handling of the C stack frames in Windows is missing something that causes a STATUS_STACK_BUFFER_OVERRUN when it shouldn't. Uncomment the `(cd)` line to make a foreign-procedure call inside the foreign-callable function, and the problem disappears. This makes me suspect that something is missing with C stack handling on x86-64 Windows.

```
(define $with-exit-proc
  (lambda (p)
    (define th (lambda () (call/cc p)))
    (define-ftype ->ptr (function () ptr))
    (let ([fptr (make-ftype-pointer ->ptr th)])
      (let ([v ((ftype-ref ->ptr () fptr))])
        (unlock-object
         (foreign-callable-code-object
          (ftype-pointer-address fptr)))
        v))))
(define go
  (case-lambda
   [() (go 1000 37)]
   [($stack-depth $base-value)
    (define *k*)
    (define-ftype foo (function (fixnum fixnum) fixnum))
    (define f (lambda (n m)
                ;; (cd)
                (if (fx= n 0)
                    (*k* m)
                    (g (fx- n 1) (fx+ m 1)))))
    (define fptr (make-ftype-pointer foo f))
    (define g (ftype-ref foo () fptr))
    (let ([v ($with-exit-proc
              (lambda (k)
                (set! *k* k)
                (f $stack-depth $base-value)))])
      (unlock-object
       (foreign-callable-code-object
        (ftype-pointer-address fptr)))
      v)]))

(pretty-print (go))
```

**Comment by burgerrg** [comment]
@mflatt, do you have any idea what could be causing this?

This particular exception kills the process immediately. You'll see the exception in the Event Viewer under Windows Logs, Application.

```
Faulting application name: scheme.exe, version: 9.5.6.0, time stamp: 0x6185834b
Faulting module name: windows.storage.dll, version: 10.0.19041.1266, time stamp: 0x526ec56d
Exception code: 0xc0000409
Fault offset: 0x00000000001b8a0d
Faulting process id: 0x3cc
Faulting application start time: 0x01d7e8658e7e476c
Faulting application path: C:\Program Files\Chez Scheme 9.5.6\bin\a6nt\scheme.exe
Faulting module path: C:\Windows\SYSTEM32\windows.storage.dll
```

See https://devblogs.microsoft.com/oldnewthing/20190108-00/?p=100655 for details about STATUS_STACK_BUFFER_OVERRUN.

**Comment by mflatt** [comment]
I'm baffled. I do see the crash when I build without threads. But when I change the `LONGJMP` in `S_return` to

```
    jmp_buf buf;
    memcpy(&buf, CAAR(yp), sizeof(jmp_buf));
    LONGJMP(buf, 1);
```

then the crash goes away. It's as if `CAAR(yp)` is  misaligned, but the allocated address seems to be aligned just fine.

Does copying to an intermediate buffer change anything for you?

**Comment by mflatt** [comment]
The issue here may be that Chez Scheme doesn't register unwind information for generate code, and so `longjmp` cannot cooperate with exception unwinding the way it wants. I'll explore that direction.

**Comment by mflatt** [comment]
Adding support for unwind information did solve the problem on my machine.

You could try the change by building from https://github.com/racket/ChezScheme. If that works for you, and if the commit at https://github.com/racket/ChezScheme/commit/e2e2cf1ce08b5152dc62eb7d6b570c3a50940bc2 seems like a good idea, then I could prepare a patch to this repo.

I'm ambivalent about the change. On the one hand, it's the Right Thing — or at least the Right Direction, because the unwind information fakes some things that `longjmp` doens't care about. Also, the implementation is not so bad. But if supporting enough unwind information had been significantly more difficult, I'd recommend just having a separate `setjmp`/`longjmp` implementation that circumvents the Microsoft implementation. That's effectively what the MinGW build does, and it's what Racket BC (pre-Chez Scheme port) does even when building with MSVC.

**Comment by mflatt** [comment]
One problem with the current implementation: the unwind information makes sense during a `longjmp`, but not at most other times, so it currently breaks unwinding to reach the exception handler installed in `S_generic_invoke` when there's an invalid memory reference. That can be fixed by moving the place where shadow space is allocated for a C function call.

**Comment by mflatt** [comment]
Ok, nevermind. :) I was overlooking arguments that don't fit in registers for foreign calls, and in that case, the attempt to approximate unwind information isn't right or close enough.

I'm now convinced that generating unwind information is too complicated to be worthwhile, and my current recommendation is to use a hand-rolled `setjmp`/`longjmp` that doesn't try to cooperate.

**Comment by burgerrg** [comment]
Thank you for figuring out what was going on!

I tried the local jmp_buf with memcpy, and it worked on my machine, but it didn't work with the github actions VM.

Do you have any recommendations for a setjmp/longjmp implementation that will work on Win64?

**Comment by mflatt** [comment]
Here's what I have in place currently for the Racket branch:

https://github.com/racket/ChezScheme/blob/db2ccadfd20aac26ca48a85890d45916d002b233/c/schlib.c#L317

https://github.com/racket/ChezScheme/blob/db2ccadfd20aac26ca48a85890d45916d002b233/c/types.h#L531

https://github.com/racket/ChezScheme/blob/db2ccadfd20aac26ca48a85890d45916d002b233/c/version.h#L162

https://github.com/racket/ChezScheme/blob/db2ccadfd20aac26ca48a85890d45916d002b233/c/scheme.c#L999


That machine code is the assembled form of https://github.com/racket/racket/blob/master/racket/src/bc/src/mzsj86w64.S (but extracted via `objdump`, so that's why the assembly in comments is AT&T style instead of Intel style).

**Comment by mflatt** [comment]
That approach maybe tries too hard to avoid pulling an assembler into the build process. Calling `ml64.exe` from a makefile isn't so bad.

**Comment by burgerrg** [comment]
@mflatt, thank you very much for the assembly code and suggestion for ml64.exe from the makefile! I added instructions to save and restore the x87 FPU control word per [Microsoft's x64 calling convention](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170#fpcsr). See https://github.com/cisco/ChezScheme/pull/600 for details.
