### ISSUE TITLE
(compile-file "syntax.ss" "syntax.patch") not work 

### ISSUE THREAD

**Issue by xingzheone** [cisco/ChezScheme#642]
```
root@hasee-pc:/mnt/e/clojure/luminusweb/chezscheme/a6le/s# scheme cmacros.so
fengea 准备 syntax-case
Chez Scheme Version 9.5.9
Copyright 1984-2022 Cisco Systems, Inc.

> (subset-mode 'system)
> (current-expand (lambda args (apply sc-expand args)))
> (optimize-level 2)
> (load "priminfo.ss")
> (load "syntax.ss")
> (compile-file "syntax.ss" "syntax.patch")
compiling syntax.ss with output to syntax.patch
Exception: attempting to re-install compile-time part of library (nanopass)
Type (debug) to enter the debugger.
```

**Comment by dybvig** [comment]
I suggest you don't try to build syntax.patch interactively but instead try just running `make` in the `s` directory after changing syntax.ss.  If this doesn't work, you might have to use cross compilation as follows.

- create a new work area for a base build in a fresh clone: `configure --workarea=base-build`
- make the new base-build work area: `make`
- create a new work area for your changes in the same clone: `configure --workarea=play`
- make the new play work area: `make`
- move into the play work area's `s` directory: cd play/s
- make a local copy of syntax.ss: rm syntax.ss; cp ../../s/syntax.ss .
- edit the local copy of syntax.ss to make the changes you want to try
- rebuild the `s` directory using cross-compilation:
```
make -f Mf-cross --jobs=2 m=a6le xm=a6le base=../../base-build
```
If the last step fails, edit syntax.ss to fix the problem and rerun just the last step.  If it is successful, test to see if the boot file loads using 
```
SCHEMEHEAPDIRS=../boot/%m ../bin/scheme
```
If this works, you can now run `make allx` in the `s` directory to complete the bootstrapping, then run the tests in the `mats` directory.   You'll want to add new tests and/or modify some existing tests to check the changes you've made.  Ideally, you should make these changes locally in the work area.

As long as you don't make any changes in the root directory you should not need to redo anything except for the `make -f Mf-cross` step, though if you have run `make allx` since the last `make -f Mf-cross ...` you'll have to run `make clean` first.

One you're happy with the changes, you can use the top-level `checkin` script to move your changes from the work area to the root directory.

**Comment by xingzheone** [comment]
thanks dybvig professor . 
I will try my best to experiment
