### ISSUE TITLE
bootstrapping on BSD?

### ISSUE THREAD

**Issue by rain-1** [cisco/ChezScheme#7]
Hello, thank you so much for releasing this!

I am using OpenBSD and I was studying the makefiles and such to try to cross compiler or bootstrap it from a binary off http://www.scheme.com/download/

I'm not having any success though! The petite chez scheme does not run (I think it built for an older version).

Would it be possible to release files to allow bootstrap or cross compile for openbsd?

**Comment by dybvig** [comment]
It has been a few years since we've tried to build on OpenBSD, FreeBSD, NetBSD, or OpenSolaris, and some of the bits have likely rotted.  If you want to give it a try, you'll need to use a host machine supporting one of the currently working machine types to create the boot and header files, debug whatever comes up in that process, then copy the boot files to the target machine and debug whatever comes up when building the executable there.

Here are steps for building the boot and header files, assuming, for concreteness, the host is 64-bit Linux and the target is 64-bit OpenBSD.  Replace the machine types (a6le and a6osx) with different machine types as appropriate for your situation.

```
./configure
make 
./workarea a6ob
(cd a6ob/s ; make -f Mf-cross m=a6le xm=a6ob base=../../a6le)
```

This should leave the boot and header files in a6ob/boot/a6ob, which you can copy to the target machine's boot/a6ob to complete the build.  On the target machine, you can update configure to recognize the target machine following the pattern of the existing entries, then run configure and make as usual.  If you don't feel like updating configure, ./configure -m=a6ob might work once the boot and header files are in place.

**Comment by rain-1** [comment]
Awesome that worked like a dream! I just had to double time-t-bits and use gmake instead of make.

I don't have the tests succeeding yet but I'm working on it.

https://github.com/rain-1/ChezScheme

**Comment by dybvig** [comment]
Here's another approach, a bit simpler:

```
./configure
make
mkdir boot/a6ob
(cd a6le; make -f Mf-boot a6ob.boot)
```

This should leave boot & header files for a6ob in boot/a6ob.

[This commit](https://github.com/cisco/ChezScheme/commit/f81024e4979da28502ae634181b379083e419911) now describes this approach in the `'make bootfiles'` description.

Now that this is documented, I'm closing the issue.
