### ISSUE TITLE
Split (chezscheme) into a part that is portable and a part that depends on Chez-specific primitives

### ISSUE THREAD

**Issue by DemiMarie** [cisco/ChezScheme#75]
The `(chezscheme)` library is large and monolithic.

It would be helpful to split it up into:
- Implementations of SRFIs, in their respective libraries.
- Chez-specific code that does not depend on Chez-specific primitives (and thus could be used elsewhere), which might belong in an external library.  One such library that has already been factored out is the nanopass framework.
- Libraries tightly integrated with Chez Scheme that cannot be reasonably provided elsewhere.  These should stay under `(chezscheme)`, or perhaps split into smaller libraries under `(chezscheme)`.

The libraries that are split out of `(chezscheme)` should probably be reexported from `(chezscheme)` for backwards compatibility.

**Comment by dybvig** [comment]
There are a couple of issues here.  One issue is whether some of the built-in subsystems or individual features should be moved from core into external libraries.  That will have to wait until there's a good repository for Chez Scheme libraries and a good mechanism for accessing it.  Even with that, some things that could theoretically move out won't because they support other things in the core or can be implemented more efficiently within the core.

The other issue is whether the `(chezscheme)` library should continue to export everything in the core.  The `(chezscheme)` library is useful when one just wants to write code and doesn't want to figure out which libraries are needed to access to a built-in binding.  To serve that purpose, it needs to remain universal and so must export not only all current bindings but also all future (core) bindings.

In any case, defining additional libraries that export the (core) bindings of individual subsystems is a fine idea; for example, an additional library for the SRFI 19 time-and-date procedures could be useful.

The nanopass library is not a good example, incidentally, since it defines bindings that aren't built in and, more importantly, is and always has been a separate project and code base.
