### ISSUE TITLE
Unguarded malloc in S_create_thread_object

### ISSUE THREAD

**Issue by laqrix** [cisco/ChezScheme#77]
Inside c/thread.c, the malloc of the tc structure is not checked.  I believe forking a large amount of threads in 32-bit mode should cause the malloc to fail, then the memcpy that follows to crash the system.

Based on the notes above S_create_thread_object, it is not clear that the normal error handling procedures work here as they may allocate memory along the way.  The tc_mutex is also currently allocated and would likely not be released without special effort.

Can the call sites adequately handle a malloc failure properly? Perhaps the caller should allocate the memory, and pass the resulting pointer into S_create_thread_object.  If it's NULL, then there's no need to copy.

I haven't chased the details of vector_in or cons_in, but is it possible they can also return invalid values for thread creation?

**Comment by dybvig** [comment]
The `malloc` result should definitely be checked, because `memcpy` might do worse than crash the system when passed a null pointer.  It should be fine for `S_create_thread_object` to call `S_error` to report a `malloc` failure when `S_create_thread_object` is called from the parent thread via `S_fork_thread`, but it's worth thinking about what happens when `S_create_thread_object` is called from the child thread via `Sactivate_thread`.  Nothing good, probably, because `Sactivate_thread` sets the thread context to the base thread's context, which the new thread has no business using.  `Sactivate_thread` should probably set the thread context to null rather than the base thread context before calling `S_create_thread_object`, with the latter taking the parent thread context as an argument, and with `do_error` in schsig.c going the `errors_to_console` route when the thread context is null.  Then `S_create_thread_object` can use `S_error` to report a `malloc` failure.  We'd need to make sure `S_create_thread_object` can't lead to other references to the thread context that will fail if it's set to null.

**Comment by laqrix** [comment]
Reviewing more code, there is another unguarded malloc in io.c at the bottom of `S_malloc_pathname`, again followed by memcpy.  And one in schlib.c, `S_call_help` the usage of `CREATEJMPBUF` which appears to be defined as `malloc`.

**Comment by dybvig** [comment]
Those should also be addressed.  I will fix these when I get the chance but will be just as happy if someone beats me to it.

**Comment by akeep** [comment]
I'll take this one.  I've got the changes to the three files underway right now.

I need to run tests and make sure I've not broken anything with this change (but, I'd be surprised if this small change creates problems).

**Comment by akeep** [comment]
The most recent commit fixes these three unchecked malloc locations, thanks for reporting the problem!
