### ISSUE TITLE
Consider a maximum heap size parameter

### ISSUE THREAD

**Issue by laqrix** [cisco/ChezScheme#78]
On Windows there does not appear to be a way to limit a process's memory usage.  In 64-bit mode, if I write bad code which allocates a lot of memory, Windows will cause the rest of the system to become unresponsive -- making it difficult to terminate the current Scheme process.  Would it be useful to have a (maximum-heap-size) parameter that is checked and allows Chez to display "out of memory" and call S_abnormal_exit?

If a parameter were to exist, would the checks be limited to where membytes is incremented in segment.c?  Are there other allocations that need to be considered? Does this have any unintentional impact on threaded mode?  Could this be useful in low-memory environments too?

**Comment by dybvig** [comment]
Having used ulimit on other operating systems to deal with this sort of problem, I can understand the frustration of dealing with an operating system or shell that doesn't provide such a mechanism, but I'm not excited about adding a mechanism to Chez Scheme, first because it's otherwise unnecessary, and second because it would necessarily be incomplete, in that it wouldn't be appropriate to track all allocation by a process, just the allocation for which Chez Scheme is directly responsible.  A quick web search turned up a couple of third-party tools you might be able use for this purpose, and not only for Scheme programs.

**Comment by laqrix** [comment]
That's fair. I have run into a similar issue with a foreign library that liked to do large allocations.  You're right, I would need that mechanism for that foreign code as well.

**Comment by pchiusano** [comment]
@dybvig question about this, will Chez behave nicely with `ulimit`, so that if the limit is reached, it will trigger more aggressive GC? The thing I'd like to avoid is needlessly crashing the process just because Chez has allocated some memory but hasn't yet run GC.
