### ISSUE TITLE
Macports packaging issues

### ISSUE THREAD

**Issue by wbl** [cisco/ChezScheme#82]
I'm working on making ChezScheme availible in macports. Unfortunately this requires linking against macports zlib, not the vendored one. Is there a configuration option for this/is there a reason it is vendored? 

Also it seems the $CC environmental variable is not honored, and we'd like it to be.  There was also a problem with build and configure downloading things, but that seems to be a more a nice to avoid. We have our own mirroring system.

The ticket in Macports is https://trac.macports.org/ticket/51863.

**Comment by dybvig** [comment]
Thanks for working on this.  It would be nice to have Chez Scheme available via macports.

Honoring the CC variable (preferably at configure time, ala CFLAGS, CPPFLAGS, and LDFLAGS) seems like a reasonable and straightforward change to make.  Feel free to make the change yourself and put in a pull request or let me know if you'd prefer we do it.

The complaints about zlib in the ticket are due to a couple of misunderstandings.  First, we link statically against libz.a, so the install location for the dynamic library is irrelevant.  Second, X11 is required by the expression editor, not by zlib.  So I would push back on this so we don't have to hook the configure / build process to support other mechanisms for including zlib.

That begs the question about the X11 include files.  The reason why they're needed by the expression editor is covered in the discussion of [issue 9](https://github.com/cisco/ChezScheme/issues/9).  The macports version should support use under X11 if possible.  If compiling against the X11 libraries is not possible, we'll have to provide a way to build without X11 and leave Xquartz users with a choice between using macports to install Chez Scheme or getting full functionality.

**Comment by wbl** [comment]
I will try to modify the Makefile.in appropriately to honor CC. 

I see your point about zlib, and will add X as a dependency. I think that will be enough, but will check with the committers to Macports.

**Comment by ryandesign** [comment]
MacPorts contains all of Xquartz, in separate ports for each X library, so it's no problem for the ChezScheme port @wbl is developing to declare dependencies on whatever X libraries it needs.

MacPorts, and macOS in general, prefers dynamic linking over static linking. ChezScheme should dynamically link to MacPorts zlib, not download and build its own copy.

Generally, all fetching of data from the Internet should be done by MacPorts during the fetch phase, not by the build system during later phases.

**Comment by wbl** [comment]
Looks like I won't get to the CC issues anytime soon, so you might be able to solve them faster.

**Comment by wbl** [comment]
Okay, I have some more time now to work on this. Are all of @ryandesign's things still issues? I've got the X dependence declared, but am unsure how to fix the fetch issue.

**Comment by TisonKun** [comment]
With https://github.com/macports/macports-ports/commit/d4ef3b6f3b36379d28f7c26dc67ec7d767efd66b I think this issue is fixed.

cc @wbl @ryandesign @dybvig

**Comment by jltaylor-us** [comment]
Is this issue resolved?

**Comment by wbl** [comment]
It's in MacPorts now, so I think so.
