### ISSUE TITLE
guard form does not appear to be R6RS compatible

### ISSUE THREAD

**Issue by ChrisVine** [cisco/ChezScheme#87]
R6RS and SRFI-34 say that if there is no matching handler clause in the guard form for a particular exception, the exception condition is re-raised as if by raise.  Kent Dybvig's TSPL says that it is re-raised as if by raise-continuable, which is wrong if intended to follow R6RS.  R7RS initially said it was re-raised as if by raise-continuable, but this was corrected in an erratum so as to be the same as R6RS and SRFI-34 (erratum 17).

It is rare for a situation to arise where this is relevant, as on re-raising an exception condition, that would usually be handled in another guard form further up the stack, or if there is none terminate the program.  But there are situations where the outcome (raise versus raise-continuable) makes a difference, such as in the code below.

The code below shows that in fact chez-scheme does neither what R6RS says (re-raise with raise) nor what TCPL says (re-raise with raise-continuable).  It ends up re-raising a non-continuable exception with raise, and re-raises a continuable exception with raise-continuable.

Although, when a non-continuable exception is thrown by the code below within a guard form, the program exits with a &non-continuable exception error when the with-exception-handler handler lambda finally exits, it is in fact a little more complicated than that.  If extra instrumentation is added, it seems that the with-exception-handler handler lambda is entered as many times as there are nested guard forms further down the stack (twice in the code below) with what appear to be continuable exceptions and then, after the exception handlers established by the guard forms have been exhausted, by a non-continuable exception.)

```
(define (raise-proc1)
  (raise-continuable 'test)
  (display "Returning from raise-proc1\n"))

(define (raise-proc2)
  (raise 'test)
  ;; we will never reach here
  (display "Returning from raise-proc2\n"))

(define (guard-proc-inner f)
  (guard (c
 	  (#f #f))
 	 (f))
  (display "Returning from inner re-raised continuable exception\n"))

(define (guard-proc-outer f)
  (guard (c
 	  (#f #f))
 	 (guard-proc-inner f))
  (display "Returning from outer re-raised continuable exception\n"))

(with-exception-handler
 (lambda (k)
   #f)
 (lambda ()
   (guard-proc-outer raise-proc1)))

(display "Normal exit\n\n")

(with-exception-handler
 (lambda (k)
   #f)
 (lambda ()
   (guard-proc-outer raise-proc2)))

;; never executed
(display "Normal exit\n\n")
```

**Comment by akeep** [comment]
Hey @ChrisVine,

Thanks for the bug report.  This is actually something that was changed in the Errata for R6RS (see the errata for section 7.1) http://www.r6rs.org/r6rs-errata.html

It actually does specify that raise-continuable should be used:

> The sentence
> "If every <cond clause>'s <test> evaluates to #f and there is no else clause, then raise is re-invoked on the raised object [...]"
>
> should be replaced by
> "If every <cond clause>'s <test> evaluates to #f and there is no else clause, then raise-continuable is invoked on the raised object [...]"

Chez Scheme is consistent with the Errata.

**Comment by ChrisVine** [comment]
What a mess.  R6RS and R7RS issuing errata in opposite directions.

However, the test case posted appears to show that with non-continuable exceptions, raise is (in the end) re-invoked on the raised object.  Is that consistent with the Errata?

**Comment by akeep** [comment]
The interesting thing is that the R7RS errata seems to indicate it was changed to be compatible with R6RS, so I think there was some miscommunication on that part of the standard (and the errata).

So, I believe the test shows the correct behavior.  Adding a print statement to your handlers might make it a little bit more clear what is going on.  Here is my understanding after reading the R6RS documentation on ``guard``, ``raise``, ``raise-continuable``, and ``with-exception-handler``.

So, imagine a simpler situation:

```
(with-exception-handler
  (lambda (x) (printf "first handler invoked with ~s\n" x) #f)
  (lambda ()
    (guard (c [#f #f]) (raise-continuable 'a))))

(printf "returned from continuable exception\n")

(with-exception-handler
  (lambda (x) (printf "second handler invoked with ~s\n" x) #f)
  (lambda ()
    (guard (c [#f #f]) (raise 'b))))

(printf "I should never be printed!\n")
```

This prints:

```
first handler invoked with a
returned from continuable exception
second handler invoked with b
second handler invoked with #<condition &non-continuable>
Exception occurred with condition components:
  0. &non-continuable
Type (debug) to enter the debugger.
```

As I read the standard, this is what I expect.  The first expression invokes ``raise-continuable`` with ``'a`` which causes the exception handler created by ``guard`` to be invoked.  Because the ``guard`` expression does not handle the exception, it re-raises ``'a`` with ``raise-continuable`` causing the handler established by the first ``with-exception-handler`` to be invoked with ``'a``.  This prints:
```
first handler invoked with a
```
Since the inner-most call was a ``raise-continuable`` we're done and we print our next line out:
```
returned from continuable exception
```

Now we head into the second exception handler which has a ``raise`` at the core.  So, the ``raise`` is called with ``'b`` invoking the handler established by the ``guard`` expression.  Since the ``guard`` again doesn't know how to handle the exception it calls ``raise-continuable`` on ``'b`` invoking the handler established by the second ``with-exception-handler``, and we get:
```
second handler invoked with b
```
Now, we're done with that handler, but the inner-most ``raise`` is not done, it still needs to call ``raise`` on a non-continuable condition on the handler one level up from the handler we established with ``guard``.  This recursive call to ``raise`` immediately invokes the handler established in the second ``with-exception-handler`` and we get:
```
second handler invoked with #<condition &non-continuable>
```
Since ``raise`` called itself recursively, and there are still more handlers on the handler stack (in this case Chez Scheme's outer-most handler.  The recursive call to ``raise`` with the non-continuable condition recurs to ``raise`` again on the next handler in the handler stack (the outer-most handler),  and we get:
```
Exception occurred with condition components:
  0. &non-continuable
Type (debug) to enter the debugger.
```
The ``Type (debug)`` line is there because I ran this within the REPL and it establishes a handler that prints this message and returns to the REPL prompt.

I think the core idea here is that even though ``guard`` calls ``raise-continuable`` (and you can see that for yourself in ``s/exception.ss`` in the ``$guard`` procedure), this cannot make a non-continuable raise continuable.

With all of this said, this doesn't prevent us from catching a non-continuable exception, determining what we want to do with it, and carrying on execution.  We just cannot continue from the point at which the ``raise`` was invoked.

**Comment by ChrisVine** [comment]
OK I am grateful for your analysis.  I assumed the explanation for chez-scheme's behaviour was something like that.  However the idea that "... the inner-most raise is not done, it still needs to call raise on a non-continuable condition on the handler one level up from the handler we established with guard" does not seem to me to be the more obvious reading of R6RS with the erratum applied to it.

On an ordinary reading of the R6RS text (with erratum) "... If every \<cond clause\>'s \<test\> evaluates to #f and there is no else clause, then raise-continuable is invoked on the raised object within the dynamic environment of the original call to raise except that the current exception handler is that of the guard expression", it seems to me that the re-invocation is intended to be substitutional: that is how it behaves where the original exception was raised with raise-continuable - a continuable exception is not handled twice in your example (or three times in mine); nor is it intended that there would be multiple exceptions in my example of two nested guard forms if the inner form does not handle a non-continuable exception (so generating a continuable exception) but the outer form does handle the exception.

Anyway, testing guile and kawa, the only other schemes to which I have access which purport to have some measure of R6RS support, they in fact re-raise with raise rather than raise-continuable.

In addition they re-raise without, when doing so, restoring the dynamic environment to that of the original call to raise (the failure to do so is both sensible and more efficient if the exception is re-raised with raise).  Thus, the following code:

```scheme
(guard (c
	[#t #f])
       (guard (c
	       [#f #f])
	      (dynamic-wind
		  (lambda () (display "in "))
		  (lambda ()
		    (raise 'test))
		  (lambda () (display "out ")))))
```

correctly prints 'in out in out' with chez-scheme by virtue of re-entry into the dynamic-wind block when the inner guard form fails to handle the exception, but only 'in out' with guile or kawa (the kawa documentation quotes R6RS with erratum applied, but does not in fact comply with it).  From its documentation, racket also appears to behave like guile and kawa when in R6RS mode, although I have not tested that.

As a side issue, raise-continuable is in my opinion more or less useless.  The idea that code further up the stack will have a better idea about how to handle an exception *before continuing back down the stack again* than the code which *is* down the stack, is contrary to all practical experience.  It seems to be inspired by common lisp restarts, the only practical use of which I have seen is in REPLs and debuggers.

From that point of view, apart from efficiency the issue disappears.  Decent code employing with-exception-handler will either carry out clean-up and logging before terminating the program if it cannot handle the exception, or handle the exception and then continue by invoking an explicit continuation object.  For such code, it doesn't matter whether the exception is continuable or not.

**Comment by dybvig** [comment]
The intent is for `guard` not to ruin a continuable exception by using `raise` to re-raise an exception that might have been raised by `raise-continuable`.  It's not to convert a `raise` into a `raise-continuable`.  When you use `raise`, you get to assume it will never return.

To your point about the utility of `raise-continuable`, it's useful for issuing warnings (including via `warning`, `warningf`), i.e., raising non-fatal exceptions, while allowing the dynamic context the opportunity to display them, treat them as errors, or ignore them.  One can also use it to allow the dynamic context more control over what the code raising the exception should do.  For example, a library routine might raise a continuable exception when it can't find a required file and allow the dynamic context to supply one, possibly by querying the user.

**Comment by ChrisVine** [comment]
@dybig: Thanks, I can see the sense in that, so long as it is thought that continuable exceptions may actually be used.

Anyway, the implementation in section 7.3 of R7RS (in the absence of the possibly incorrect R7RS erratum) behaves in the way chez-scheme does so I think it must be taken to be what R6RS, with the erratum to which akeep has referred, intends to occur.  It is the only scheme which, as far as I can see, actually does so.

I'll therefore close this.

**Comment by mnieper** [comment]
Just for the record: The erratum for R7RS has been retracted, so R7RS now behaves again like R6RS with the erratum for R6RS.
