### ISSUE TITLE
'(* 0 +inf.0)' should evaluate to '+nan.0'

### ISSUE THREAD

**Issue by fedeinthemix** [cisco/ChezScheme#94]
The expression '(\* 0 +inf.0)' evaluates to '0' while it should evaluate to '+nan.0'.
Evaluation of '(\* 0.0 +inf.0)' gives the expected result.

Similarly with '-inf.0'.

**Comment by ChaosEternal** [comment]
(* 0 0.0) => 0
(* 0 whatever-in-numeric-tower) => 0 ;; I am not sure, but I think so

hence
(* 0 +inf.0) => 0

mathematically, it is correct.

**Comment by akeep** [comment]
Yes, @ChaosEternal is correct, the R6RS standard allows ``(* 0 +inf.0)`` to return either ``0`` or ``+nan.0``.  The description for ``*`` in section 11.7.4.  It includes the explicit examples:

```
(* 0 +inf.0) => 0 or +nan.0
(* 0 +nan.0) => 0 or +nan.0
```

**Comment by fedeinthemix** [comment]
Thanks for your answer and the reference to the R6RS standard with an
example.  Still, *mathematically* '0 * Infinity' is not defined ('Infinity'
is not a number!). Consider the example: define f(x) = x and g(x) = 1/x.
Then you have

lim x->Infinity f(x) = Infinity
lim x->Infinity g(x) = 0

From this, if you assume that 0*Infinity is 0 you would conclude that lim
x->Infinity f(x)*g(x) = 0, but this is clearly wrong as

lim x->Infinity f(x)*g(x) = lim x->Infinity x/x = 1

I can imagine that the allowance for '(* 0 +inf.0)' in the standard comes
from a remove past where '+nan.0' didn't exist and people doing numerical
computations wanted to avoid their procedures blowing up.  But now, with
'+nan.0' we can do better and avoid (in some situations) getting wrong
results.

**Comment by soegaard** [comment]
The thing is that `+inf.0` does not represent infinity. It represents a number which happen to be so large that it can't be represented in floating point. So `(*  0 +inf.0)` just means "exact zero times a very large number" - and then it makes sense to make the result exact zero.

**Comment by fedeinthemix** [comment]
Well, Section 4.2.8 of R6RS appears to say otherwise:

"... The literals +inf.0 and -inf.0 represent positive and negative
infinity, respectively. ..."

Later (Section 11.7.4) it says that you *may* use it for the purpose
that you describe.

**Comment by dybvig** [comment]
For the most part, R6RS tries to remain representation-agnostic to allow a wide variety of implementation choices for inexact arithmetic.  One choice is to use arbitrary-precision inexact arithmetic in which all finite numbers are representable, albeit imprecisely, and in which +inf.0 and -inf.0 represent only non-finite numbers.

An implementation may, however, choose to treat finite numbers as +inf.0 and -inf.0 if they are out of that implementation's representable range.  The exact zero value of (* 0 +inf.0) derives from that choice: in such an implementation, +inf.0 and -inf.0 most often represent out-of-range finite numbers, and multiplying such numbers by exact 0 should produce exact 0.

A program needing infinities that never represent mere out-of-range finite numbers isn't well served by this.  My guess is such programs aren't common, aren't well-served anyway by a single pair of infinities representing all cardinalities, and might even require some form of symbolic arithmetic.

**Comment by fedeinthemix** [comment]
I see your point of view.  However, in my opinion it is dangerous to give
as result of a computation a definitive answer which may or may not be
correct. By returning +nan.0 instead of 0 one would warn the user that
something may be wrong. If somebody is trying to use finite numbers that
can't be represented by the computer system, from my point of view
something is definitely wrong.

By the way, out of curiosity, I've checked MATLAB, Numpy and Octave which
are the most widely used systems for numerical computations and they all
return NaN.

**Comment by burgerrg** [comment]
@fedeinthemix, as long as you use inexact (floating-point) numbers, it behaves as you'd expect, namely, (* 0.0 +inf.0) => +nan.0

In my experience, the most common scenario is code that multiples two variables, each of which is bound to an inexact number.

**Comment by ChaosEternal** [comment]
Mathematically,
0 * limit(x->0, 1/x) => 0 rather than undefined.

and infinite-small * infinite-large  => Undefined

**Comment by fedeinthemix** [comment]
Of course there are *examples* where a careful mathematical analysis gives
a result which looks like 0*infinity = 0.

However, when you only see 0*infinity you do not have enough information to
tell if this is one of those examples or not. In particular, given the
applicative-order evaluation of Scheme, '(* 0 +inf.0)' can be a partial
evaluation of some arbitrary expression.
Here an example:

(define (f x) x)
(define (g x) (/ 1.0 x))
(* (f 0) (g 0))
=> 0 ;; wrong!!

**Comment by dybvig** [comment]
What's wrong here is that `(/ 1.0 0)` evaluates to `+inf.0.`  It should be an error or at least `+nan.0` since (a) it is division by exact zero, not something arbitrarily close to zero, and (b) the sign is indeterminate since exact 0 is neither positive nor negative.  R6RS, however, requires (/ 1.0 0) to return +inf.0 under the assumption that 0 is first converted to +0.0.

`+inf.0 `and `-inf.0` shouldn't be used when something "went wrong", as in this example.

**Comment by fedeinthemix** [comment]
From my point of view, as somebody who was not involved in writing R6RS,
but who reads its outcome, section 4.2.8 and the requirement that (/ 1.0 0)
should evaluate to +inf.0 implies that the latter means infinity (and not
arbitrarily large, but not infinity). The matter of sign comes down to
convention (this must be for every function with discontinuities).

Making a distinction between infinity and a symbol which stands for
"arbitrarily large, but not infinity", and zero and "arbitrarily small but
not exact zero" leads to more problematic cases. For example why does (= 0
0.0) evaluates to #t if (* 0 +inf.0) gives a result different from (* 0.0
+inf.0)? Should this (< -0.0 0 0.0) evaluate to #t then?

If you treat 0.0 as 0 and not "arbitrarily close to zero" (the limit of 1/x
for x->0 is exactly zero, not arbitrarily close to it) and +inf.0 as
infinity then (= 0.0 0) is naturally #t, (< -0.0 0 0.0) naturally #f and (*
0 +inf.0) and (* 0.0 +inf.0) should both evaluate to +nan.0 without
inconsistencies.

Maybe I just didn't come across cases where this interpretation would lead
to difficulties. In that case I would be grateful for concrete examples.

**Comment by dybvig** [comment]
Should -0.0 also be treated as 0?

**Comment by fedeinthemix** [comment]
Yes, like it is common in mathematics 0.0 should mean 0 reached from the
positive side (lim x->+0 f(x)) and -0.0 should mean 0 reached from the
negative side (lim x->-0 f(x)). This adds a piece of information to help
with the evaluation of functions with discontinuities and in particular
with singularities.

**Comment by dybvig** [comment]
And what is the value of (/ 1.0 -0.0)?

**Comment by fedeinthemix** [comment]
The value of (/ 1.0 -0.0) should be -inf.0 as currently given and in
accordance with lim x->-0 1/x.

**Comment by dybvig** [comment]
Your third note back claims it's problematic for `(* 0 +inf.0)` to give a different result from `(* 0.0 +inf.0)` when `(= 0 0.0)` evaluates to #t.  By the same logic, it's equally problematic for `(/ 1.0 0)` to give a different result from `(/ 1.0 -0.0)` when `(= 0 -0.0)` evaluates to #t, yet that's what your second and first notes back require.  So your interpretation is problematic or your logic is flawed.  In this issue, your logic is flawed: numeric equality is inherently imprecise when inexact numbers are involved and does not imply identical behavior.  There are many cases where the behavior of numerically equal numbers can differ.  For example, `(= 10 10.0)` => #t, but `(= (/ 1 10) (/ 1 10.0))` => #f.

Your interpretation has a flaw as well, because R6RS calculations treat `0.0` differently from `0` in more than the one case you brought up originally, precisely because 0 is exactly 0 and 0.0 is not.  A trivial example is that `(- 0)` => `0` while `(- 0.0)` => `-0.0`.  A particularly relevant example is that `(/ 1 0)` raises an exception while `(/ 1 0.0)` does not.  Also, as has been [observed recently](https://github.com/cisco/ChezScheme/issues/95), an inexact zero imaginary part makes a complex number non-real, while an exact zero imaginary part does not.  This difference shows up in calculations, too, e.g., `(cos 0.0+0i)` = `(cos 0.0)` => `1.0` while `(cos 0.0+0.0i)` => `1.0-0.0`.

The possibility of other interpretations aside, I remain comfortable with the interpretation that `+0.0` and `-0.0` are close to but not quite zero and `+inf.0` and `-inf+0` are large but not quite infinity.  My preference for this interpretation reflects (a) the fact that `+inf.0` and `-inf.0` can arise through overflow or through underflow followed by division and (b) my suspicion that they arise this way much more often than through the intentional introduction of a true infinity.  So I remain convinced that, in Chez Scheme, `(* 0 <any number>)` should continue to evaluate to `0`, which R6RS allows, and `(/ <any number> 0)` should raise an exception, which R6RS does not allow---though I'm tempted to arrange for the version of `/` exported from the `(chezscheme)` library to do so.

**Comment by fedeinthemix** [comment]
On Mon, Aug 22, 2016 at 5:44 AM, R. Kent Dybvig <notifications@github.com>
wrote:

> Your third note back claims it's problematic for (* 0 +inf.0) to give a
> different result from (* 0.0 +inf.0) when (= 0 0.0) evaluates to #t. By
> the same logic, it's equally problematic for (/ 1.0 0) to give a
> different result from (/ 1.0 -0.0) when (= 0 -0.0) evaluates to #t, yet
> that's what your second and first notes back require.
>
Not exactly: I said that (/ 1.0 0) and (/ 1.0 0.0) should mean lim x->+0
1/x, while (/ 1.0 -0.0) should mean lim x->-0 1/x. The numbers 0, 0.0 and
-0.0 should all be the same exact number but they carry an extra piece of
information to tell from which side you reached it. That's just borrowing
notation from mathematics.

> So your interpretation is problematic or your logic is flawed. In this
> issue, your logic is flawed: numeric equality is inherently imprecise when
> inexact numbers are involved and does not imply identical behavior. There
> are many cases where the behavior of numerically equal numbers can differ.
> For example, (= 10 10.0) => #t, but (= (/ 1 10) (/ 1 10.0)) => #f.
>
That's very revealing! It seems that mixing exact and inexact numbers
always leads to surprises.

> Your interpretation has a flaw as well, because R6RS calculations treat
> 0.0 differently from 0 in more than the one case you brought up
> originally, precisely because 0 is exactly 0 and 0.0 is not. A trivial
> example is that (- 0) => 0 while (- 0.0) => -0.0. A particularly relevant
> example is that (/ 1 0) raises an exception while (/ 1 0.0) does not.
> Also, as has been observed recently
> <https://github.com/cisco/ChezScheme/issues/95>, an inexact zero
> imaginary part makes a complex number non-real, while an exact zero
> imaginary part does not. This difference shows up in calculations, too,
> e.g., (cos 0.0+0i) = (cos 0.0) => 1.0 while (cos 0.0+0.0i) => 1.0-0.0.
>
Thanks for the examples.

> The possibility of other interpretations aside, I remain comfortable with
> the interpretation that +0.0 and -0.0 are close to but not quite zero and
> +inf.0 and -inf+0 are large but not quite infinity. My preference for
> this interpretation reflects (a) the fact that +inf.0 and -inf.0 can
> arise through overflow or through underflow followed by division and (b) my
> suspicion that they arise this way much more often than through the
> intentional introduction of a true infinity. So I remain convinced that, in
> Chez Scheme, (* 0 <any number>) should continue to evaluate to 0, which
> R6RS allows, and (/ <any number> 0) should raise an exception, which R6RS
> does not allow---though I'm tempted to arrange for the version of /
> exported from the (chezscheme) library to do so.
>
I decided to open an issue by seeing the result of (* (f 0) (g 0)) with f
and g as given on a previous note which is definitely a wrong result. I
thought that changing (* 0 +inf.0) from 0 to +nan.0 was a simple solution,
but I see that peoples disagree. To me what matters is to minimize the
number of times that a computation can lead to a wrong result. Rising an
exception as you suggest is one such method and is fine with me.

**Comment by dybvig** [comment]
I'm closing this discussion but welcome a pull request that causes `(/ <any number> 0)` to raise an exception when `/` is imported from `(chezscheme)` rather than `(rnrs)`.
