### ISSUE TITLE
(real? 7.0+0.0i) return #f ???

### ISSUE THREAD

**Issue by luohaha** [cisco/ChezScheme#95]
`(real? 7.0+0.0i)` return `#f`, but `(real? 7.0+0i)` return `#t`.
Also happen when using `rational?` and `integer?`

**Comment by ChaosEternal** [comment]
(eq? 0.0 0) => #f 
hence
(eq? 0+0.0i 0) => #f 
hence
(real? 0+0.0i ) => #f 
then
(real? 7.0+0.0i ) => #f

**Comment by luohaha** [comment]
@ChaosEternal 
(eq? 0+0.0i 0) => #f can't draw a conclusion that (real? 0+0.0i ) => #f

**Comment by ChaosEternal** [comment]
that means you can not ignore the imaginary part of that complex, no matter how small of its distance from zero, it is not ZERO.

zero is zero, but 0.0 is something different from zero.

**Comment by akeep** [comment]
@ChaosEternal Unfortunately, ``eq?`` is not a good test to use when comparing numbers in general, because in some cases (for instance floating point numbers, rational numbers, etc.) the numbers are boxed, and ``eq?`` is really performing pointer equivalence.  So for instance ``(eq? 0.0 0.0)`` is also ``#f``, while both ``(= 0.0 0)`` and ``(= 0.0 0.0)`` are ``#t`` as is ``(= 0.0 -0.0)``.

That said, you are absolutely correct about ``0.0`` representing an infinitesimally small, but not necessarily ``0`` value.

@luohaha The behavior of ``(real? 7.0+0i)`` vs. ``(real? 7.0+0.0i)`` is based around this idea that ``0.0`` is not necessarily exactly ``0``.  The R6RS standard defines ``real?`` in section 11.7.4 to be:

> If z is a complex number object, then (real? z) is true if and only if (zero? (imag-part z)) and (exact? (imag-part z)) are both true.

Since ``0.0`` is not ``exact?``, ``7.0+0.0i`` cannot be ``real?``.  There is even a similar example in the description:

```
(real? -2.5+0.0i) => #f
(real? -2.5+0i)   => #t
```

**Comment by luohaha** [comment]
@akeep Thank you so much! 
I open this issue because I saw [this](http://www.scheme.com/tspl3/objects.html#./objects:h2).
There are some examples about `(real? obj)` , `(rational? obj) ` and so on.
```
(integer? 7.0+0.0i) => #t
(rational? 7.0+0.0i) => #t
(real? 7.0+0.0i) => #t
(complex? 7.0+0.0i) => #t
(number? 7.0+0.0i) => #t 
```

```
(integer? 3.2-2.01i) => #f
(rational? 3.2-2.01i) => #f
(real? 3.2-2.01i) => #f
(complex? 3.2-2.01i) => #t
(number? 3.2-2.01i) => #t 
```

**Comment by ChaosEternal** [comment]
@luohaha 

but  in tspl4 
http://www.scheme.com/tspl4/objects.html#./objects:h2

(integer? 7.0+0.0i) <graphic> #f
(rational? 7.0+0.0i) <graphic> #f
(real? 7.0+0.0i) <graphic> #f
(complex? 7.0+0.0i) <graphic> #t
(number? 7.0+0.0i) <graphic> #t

**Comment by ChaosEternal** [comment]
你这叫用前朝的剑斩本朝的官 @luohaha
